### PR TITLE
Implement conditional_merge.

### PR DESCRIPTION
**Pull request by tcsnfkx**
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/10)

### CODE REVIEW

**Review by mpatel24 — APPROVED** [review]

**Review by wliue — CHANGES_REQUESTED** [review]
> Reviewed 6 of 6 files at r1.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/10)* status: all files reviewed, 6 unresolved discussions (waiting on @efoxepstein, @EvgSkv, @kunyuchen, @lenjoy, @my2457, @oliver-amzn, and @tcsnfkx)

___
*[src/main/cc/wfa/virtual_people/core/model/attributes_updater/conditional_merge_impl.cc, line 54 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/10#-McF5iPJ7a9rOYFI9ggO:-McF5iPJ7a9rOYFI9ggP:bd6xwxz) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-core-serving/blob/da4bbb155d629a906a6f2a171a841a417bf42e18/src/main/cc/wfa/virtual_people/core/model/attributes_updater/conditional_merge_impl.cc#L54)):*
> ```cpp
>         filters.back(),
>         FieldFilter::New(LabelerEvent().GetDescriptor(), node.condition()));
>     
> ```

Seems extra spaces here.
___
*[src/main/cc/wfa/virtual_people/core/model/attributes_updater/conditional_merge_impl.cc, line 64 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/10#-McF6R8F91_vVZZlebJz:-McF6R8F91_vVZZlebK-:b-amu4x) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-core-serving/blob/da4bbb155d629a906a6f2a171a841a417bf42e18/src/main/cc/wfa/virtual_people/core/model/attributes_updater/conditional_merge_impl.cc#L64)):*
> ```cpp
>       std::unique_ptr<FieldFiltersMatcher> matcher,
>       FieldFiltersMatcher::Build(std::move(filters)));
> ```

Could also check NULL on matcher. Maybe also check filters and matcher have the same length.
___
*[src/main/cc/wfa/virtual_people/core/model/attributes_updater/conditional_merge_impl_test.cc, line 60 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/10#-McF7oNFCYdO4SRlCZr9:-McF7oNFCYdO4SRlCZrA:b-6et2j5) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-core-serving/blob/da4bbb155d629a906a6f2a171a841a417bf42e18/src/main/cc/wfa/virtual_people/core/model/attributes_updater/conditional_merge_impl_test.cc#L60)):*
> ```cpp
> }
> 
> TEST(ConditionalMergeImplTest, TestNoUpdate) {
> ```

Could add a test that fail to build a field filter.
___
*[src/main/cc/wfa/virtual_people/core/model/attributes_updater/conditional_merge_impl_test.cc, line 110 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/10#-McF81kX2FjV7aAIQHwl:-McF81kX2FjV7aAIQHwm:bvk7wuw) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-core-serving/blob/da4bbb155d629a906a6f2a171a841a417bf42e18/src/main/cc/wfa/virtual_people/core/model/attributes_updater/conditional_merge_impl_test.cc#L110)):*
> ```cpp
>       AttributesUpdaterInterface::Build(config));
> 
>   LabelerEvent event_1;
> ```

Could add comments for these cases. 
___
*[src/main/cc/wfa/virtual_people/core/model/attributes_updater/conditional_merge_impl_test.cc, line 152 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/10#-McF8MH2BAmvZeEVqnem:-McF8MH2BAmvZeEVqnen:b93djyp) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-core-serving/blob/da4bbb155d629a906a6f2a171a841a417bf42e18/src/main/cc/wfa/virtual_people/core/model/attributes_updater/conditional_merge_impl_test.cc#L152)):*
> ```cpp
>       AttributesUpdaterInterface::Build(config));
> 
>   LabelerEvent event;
> ```

Could add a comment.
___
*[src/main/cc/wfa/virtual_people/core/model/attributes_updater/conditional_merge_impl_test.cc, line 230 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/10#-McF8JZHA7Ba6fC2sp7q:-McF8JZHA7Ba6fC2sp7r:b93djyp) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-core-serving/blob/da4bbb155d629a906a6f2a171a841a417bf42e18/src/main/cc/wfa/virtual_people/core/model/attributes_updater/conditional_merge_impl_test.cc#L230)):*
> ```cpp
>       AttributesUpdaterInterface::Build(config));
> 
>   LabelerEvent event;
> ```

Could add a comment.

**Review by efoxepstein — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/10)* status: all files reviewed, 7 unresolved discussions (waiting on @EvgSkv, @kunyuchen, @lenjoy, @my2457, @oliver-amzn, and @tcsnfkx)

___
*[src/main/cc/wfa/virtual_people/core/model/attributes_updater/conditional_merge_impl.cc, line 84 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/10#-McFfpjO7RDUAqqapCGZ:-McFfpjO7RDUAqqapCG_:b-aucocr) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-core-serving/blob/da4bbb155d629a906a6f2a171a841a417bf42e18/src/main/cc/wfa/virtual_people/core/model/attributes_updater/conditional_merge_impl.cc#L84)):*
> ```cpp
>     }
>   }
>   event.MergeFrom(updates_[index]);
> ```

Maybe defensively check that `0 <= index < updates_.size()`?

**Review by tcsnfkx — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/10)* status: 4 of 6 files reviewed, 7 unresolved discussions (waiting on @efoxepstein, @EvgSkv, @kunyuchen, @lenjoy, @my2457, @oliver-amzn, and @wliue)

___
*[src/main/cc/wfa/virtual_people/core/model/attributes_updater/conditional_merge_impl.cc, line 54 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/10#-McF5iPJ7a9rOYFI9ggO:-McG43OD46i2WPZem8qs:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-core-serving/blob/da4bbb155d629a906a6f2a171a841a417bf42e18/src/main/cc/wfa/virtual_people/core/model/attributes_updater/conditional_merge_impl.cc#L54)):*
<details><summary><i>Previously, wliue (Wei Liu) wrote…</i></summary><blockquote>

Seems extra spaces here.
</blockquote></details>

Done.
___
*[src/main/cc/wfa/virtual_people/core/model/attributes_updater/conditional_merge_impl.cc, line 64 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/10#-McF6R8F91_vVZZlebJz:-McG44IuCHRkSGdBZB_w:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-core-serving/blob/da4bbb155d629a906a6f2a171a841a417bf42e18/src/main/cc/wfa/virtual_people/core/model/attributes_updater/conditional_merge_impl.cc#L64)):*
<details><summary><i>Previously, wliue (Wei Liu) wrote…</i></summary><blockquote>

Could also check NULL on matcher. Maybe also check filters and matcher have the same length.
</blockquote></details>

Done.
___
*[src/main/cc/wfa/virtual_people/core/model/attributes_updater/conditional_merge_impl.cc, line 84 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/10#-McFfpjO7RDUAqqapCGZ:-McG45Mw40_NKnGuCZ20:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-core-serving/blob/da4bbb155d629a906a6f2a171a841a417bf42e18/src/main/cc/wfa/virtual_people/core/model/attributes_updater/conditional_merge_impl.cc#L84)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Maybe defensively check that `0 <= index < updates_.size()`?
</blockquote></details>

Done.
___
*[src/main/cc/wfa/virtual_people/core/model/attributes_updater/conditional_merge_impl_test.cc, line 60 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/10#-McF7oNFCYdO4SRlCZr9:-McG46ot1ja3B848a5Xz:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-core-serving/blob/da4bbb155d629a906a6f2a171a841a417bf42e18/src/main/cc/wfa/virtual_people/core/model/attributes_updater/conditional_merge_impl_test.cc#L60)):*
<details><summary><i>Previously, wliue (Wei Liu) wrote…</i></summary><blockquote>

Could add a test that fail to build a field filter.
</blockquote></details>

Done.
___
*[src/main/cc/wfa/virtual_people/core/model/attributes_updater/conditional_merge_impl_test.cc, line 110 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/10#-McF81kX2FjV7aAIQHwl:-McG47nZ2Njmx4Imovf2:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-core-serving/blob/da4bbb155d629a906a6f2a171a841a417bf42e18/src/main/cc/wfa/virtual_people/core/model/attributes_updater/conditional_merge_impl_test.cc#L110)):*
<details><summary><i>Previously, wliue (Wei Liu) wrote…</i></summary><blockquote>

Could add comments for these cases. 
</blockquote></details>

Done.
___
*[src/main/cc/wfa/virtual_people/core/model/attributes_updater/conditional_merge_impl_test.cc, line 152 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/10#-McF8MH2BAmvZeEVqnem:-McG48P75a5-28_mlV5a:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-core-serving/blob/da4bbb155d629a906a6f2a171a841a417bf42e18/src/main/cc/wfa/virtual_people/core/model/attributes_updater/conditional_merge_impl_test.cc#L152)):*
<details><summary><i>Previously, wliue (Wei Liu) wrote…</i></summary><blockquote>

Could add a comment.
</blockquote></details>

Done.
___
*[src/main/cc/wfa/virtual_people/core/model/attributes_updater/conditional_merge_impl_test.cc, line 230 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/10#-McF8JZHA7Ba6fC2sp7q:-McG48oT1JW2FtQ434dT:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-core-serving/blob/da4bbb155d629a906a6f2a171a841a417bf42e18/src/main/cc/wfa/virtual_people/core/model/attributes_updater/conditional_merge_impl_test.cc#L230)):*
<details><summary><i>Previously, wliue (Wei Liu) wrote…</i></summary><blockquote>

Could add a comment.
</blockquote></details>

Done.

**Review by efoxepstein — APPROVED** [review]
> Reviewed 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/10)* status: all files reviewed, 7 unresolved discussions (waiting on @EvgSkv, @kunyuchen, @lenjoy, @my2457, @oliver-amzn, @tcsnfkx, and @wliue)

___
*[src/main/cc/wfa/virtual_people/core/model/attributes_updater/conditional_merge_impl.cc, line 52 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/10#-McGDpTR21bvpQ5R48nm:-McGDpTR21bvpQ5R48nn:b-sfordu) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-core-serving/blob/c6cc2be91f0d26b1f2025448e60ee26355d836d1/src/main/cc/wfa/virtual_people/core/model/attributes_updater/conditional_merge_impl.cc#L52)):*
> ```cpp
>     filters.emplace_back();
>     ASSIGN_OR_RETURN(
>         filters.back(),
> ```

I think `ASSIGN_OR_RETURN(filters.emplace_back(), ...)` should work

**Review by wliue — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/10)* status: all files reviewed, 8 unresolved discussions (waiting on @EvgSkv, @kunyuchen, @lenjoy, @my2457, @oliver-amzn, @tcsnfkx, and @wliue)

___
*[src/main/cc/wfa/virtual_people/core/model/attributes_updater/conditional_merge_impl_test.cc, line 61 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/10#-McGLqtHEiLIHIvnatTk:-McGLqtHEiLIHIvnatTl:b-vir65r) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-core-serving/blob/c6cc2be91f0d26b1f2025448e60ee26355d836d1/src/main/cc/wfa/virtual_people/core/model/attributes_updater/conditional_merge_impl_test.cc#L61)):*
> ```
> // Name and value must be set for EQUAL field filter.
> ```

Could add that so this will fail to build field filter for the first node, therefore fail to build the ConditionalMerge.

**Review by tcsnfkx — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/10)* status: 4 of 6 files reviewed, 8 unresolved discussions (waiting on @efoxepstein, @EvgSkv, @kunyuchen, @lenjoy, @my2457, @oliver-amzn, and @wliue)

___
*[src/main/cc/wfa/virtual_people/core/model/attributes_updater/conditional_merge_impl.cc, line 52 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/10#-McGDpTR21bvpQ5R48nm:-McGWaA33aKS-xXJKIlT:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-core-serving/blob/c6cc2be91f0d26b1f2025448e60ee26355d836d1/src/main/cc/wfa/virtual_people/core/model/attributes_updater/conditional_merge_impl.cc#L52)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

I think `ASSIGN_OR_RETURN(filters.emplace_back(), ...)` should work
</blockquote></details>

Done.
___
*[src/main/cc/wfa/virtual_people/core/model/attributes_updater/conditional_merge_impl_test.cc, line 61 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/10#-McGLqtHEiLIHIvnatTk:-McGW_5z63sD-1TADMQd:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-core-serving/blob/c6cc2be91f0d26b1f2025448e60ee26355d836d1/src/main/cc/wfa/virtual_people/core/model/attributes_updater/conditional_merge_impl_test.cc#L61)):*
<details><summary><i>Previously, wliue (Wei Liu) wrote…</i></summary><blockquote>

> ```
> // Name and value must be set for EQUAL field filter.
> ```

Could add that so this will fail to build field filter for the first node, therefore fail to build the ConditionalMerge.
</blockquote></details>

Done.

**Pull request merged**
