### PR TITLE
Implement sparse_update_matrix.

### LINKED ISSUE #31: Implement virtual people model and labeler in C++

### PR DESCRIPTION
**Pull request by tcsnfkx**
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/9)

### CODE REVIEW

**Review by wliue — CHANGES_REQUESTED** [review]
> Reviewed 10 of 10 files at r1.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/9)* status: all files reviewed, 9 unresolved discussions (waiting on @efoxepstein, @EvgSkv, @kunyuchen, @lenjoy, @mpatel24, @my2457, @oliver-amzn, and @tcsnfkx)

___
*[src/main/cc/wfa/virtual_people/core/model/attributes_updater/sparse_update_matrix_impl.h, line 29 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/9#-McFBx_h1h77c5uayKZV:-McFBx_h1h77c5uayKZW:b-m3k69r) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-core-serving/blob/e8c0d07085a1eb9c49fb396cd1ab50a5a95b4ed6/src/main/cc/wfa/virtual_people/core/model/attributes_updater/sparse_update_matrix_impl.h#L29)):*
> ```objc
> namespace wfa_virtual_people {
> 
> class SparseUpdateMatrixImpl : public AttributesUpdaterInterface {
> ```

Could add an example to show how it works, i.e.  match a column then select a row.
___
*[src/main/cc/wfa/virtual_people/core/model/attributes_updater/sparse_update_matrix_impl.h, line 88 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/9#-McFAaSb9T0a86H84Jgz:-McFAaSb9T0a86H84Jh-:bvhl4n5) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-core-serving/blob/e8c0d07085a1eb9c49fb396cd1ab50a5a95b4ed6/src/main/cc/wfa/virtual_people/core/model/attributes_updater/sparse_update_matrix_impl.h#L88)):*
> ```objc
>   // The size of the vector is the columns count.
>   std::vector<std::unique_ptr<DistributedConsistentHashing>> row_hashings_;
>   // The seed used in hashing.
> ```

The meaning of hashing might be ambiguous. Could specify that random_seed is used during row selection after a column is matched. 
___
*[src/main/cc/wfa/virtual_people/core/model/attributes_updater/sparse_update_matrix_impl.cc, line 103 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/9#-McFNcbO9RWN4uf226Wv:-McFNcbO9RWN4uf226Ww:b2rnojv) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-core-serving/blob/e8c0d07085a1eb9c49fb396cd1ab50a5a95b4ed6/src/main/cc/wfa/virtual_people/core/model/attributes_updater/sparse_update_matrix_impl.cc#L103)):*
> ```cpp
>     ASSIGN_OR_RETURN(
>         hash_matcher,
>         BuildHashFieldMaskMatcher(config.columns(), config.hash_field_mask()));
> ```

Could check NULL.
___
*[src/main/cc/wfa/virtual_people/core/model/attributes_updater/sparse_update_matrix_impl.cc, line 106 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/9#-McFNeKz8Qx-lpByr_VV:-McFNeKz8Qx-lpByr_VW:b2rnojv) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-core-serving/blob/e8c0d07085a1eb9c49fb396cd1ab50a5a95b4ed6/src/main/cc/wfa/virtual_people/core/model/attributes_updater/sparse_update_matrix_impl.cc#L106)):*
> ```cpp
>   } else {
>     ASSIGN_OR_RETURN(
>         filters_matcher, BuildFieldFiltersMatcher(config.columns()));
> ```

Could check NULL.
___
*[src/main/cc/wfa/virtual_people/core/model/attributes_updater/sparse_update_matrix_impl_test.cc, line 159 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/9#-McFObrH-5r8H1p51cqm:-McFObrH-5r8H1p51cqn:b-3605ht) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-core-serving/blob/e8c0d07085a1eb9c49fb396cd1ab50a5a95b4ed6/src/main/cc/wfa/virtual_people/core/model/attributes_updater/sparse_update_matrix_impl_test.cc#L159)):*
> ```cpp
> }
> 
> TEST(SparseUpdateMatrixImplTest, TestOutputDistribution) {
> ```

The probability normalization is done internally, correct? Could add a test that prob doesn't sum to 1.
___
*[src/main/cc/wfa/virtual_people/core/model/attributes_updater/sparse_update_matrix_impl_test.cc, line 308 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/9#-McFP3Ni6SrFoBaL8K8e:-McFP3Ni6SrFoBaL8K8f:b93djyp) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-core-serving/blob/e8c0d07085a1eb9c49fb396cd1ab50a5a95b4ed6/src/main/cc/wfa/virtual_people/core/model/attributes_updater/sparse_update_matrix_impl_test.cc#L308)):*
> ```cpp
>       AttributesUpdaterInterface::Build(config));
> 
>   LabelerEvent event;
> ```

Could add a comment.
___
*[src/main/cc/wfa/virtual_people/core/model/attributes_updater/sparse_update_matrix_impl_test.cc, line 408 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/9#-McFPIzJ5m77l7--X0Vy:-McFPHWH71dktgKGy-a5:b-lrua6p) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-core-serving/blob/e8c0d07085a1eb9c49fb396cd1ab50a5a95b4ed6/src/main/cc/wfa/virtual_people/core/model/attributes_updater/sparse_update_matrix_impl_test.cc#L408)):*
> ```
> not matches
> ```

Nit: doesn't match
___
*[src/main/cc/wfa/virtual_people/core/model/utils/update_matrix_helper.h, line 38 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/9#-McFQsdI6y6sNydm0bjj:-McFQsdI6y6sNydm0bjk:b-3b8l48) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-core-serving/blob/e8c0d07085a1eb9c49fb396cd1ab50a5a95b4ed6/src/main/cc/wfa/virtual_people/core/model/utils/update_matrix_helper.h#L38)):*
> ```objc
> // @row_hashings.
> //
> // When no column is selected, returns {-1, -1}.
> ```

Refer to the constant kNoMatchingIndex.
___
*[src/main/cc/wfa/virtual_people/core/model/utils/update_matrix_helper.cc, line 28 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/9#-McFRZoY6moSAb5x4rpy:-McFRZoY6moSAb5x4rpz:b-qmrl99) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-core-serving/blob/e8c0d07085a1eb9c49fb396cd1ab50a5a95b4ed6/src/main/cc/wfa/virtual_people/core/model/utils/update_matrix_helper.cc#L28)):*
> ```cpp
> namespace wfa_virtual_people {
> 
> absl::StatusOr<MatrixIndexes> SelectFromMatrix(
> ```

Add a unit test.

**Review by tcsnfkx — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/9)* status: 4 of 10 files reviewed, 8 unresolved discussions (waiting on @efoxepstein, @EvgSkv, @kunyuchen, @lenjoy, @mpatel24, @my2457, @oliver-amzn, and @wliue)

___
*[src/main/cc/wfa/virtual_people/core/model/attributes_updater/sparse_update_matrix_impl.h, line 29 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/9#-McFBx_h1h77c5uayKZV:-McI9Q9t5fFPQuzdO5qO:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-core-serving/blob/e8c0d07085a1eb9c49fb396cd1ab50a5a95b4ed6/src/main/cc/wfa/virtual_people/core/model/attributes_updater/sparse_update_matrix_impl.h#L29)):*
<details><summary><i>Previously, wliue (Wei Liu) wrote…</i></summary><blockquote>

Could add an example to show how it works, i.e.  match a column then select a row.
</blockquote></details>

Done.
___
*[src/main/cc/wfa/virtual_people/core/model/attributes_updater/sparse_update_matrix_impl.h, line 88 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/9#-McFAaSb9T0a86H84Jgz:-McI9Qvu2Md3zkvI_dR3:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-core-serving/blob/e8c0d07085a1eb9c49fb396cd1ab50a5a95b4ed6/src/main/cc/wfa/virtual_people/core/model/attributes_updater/sparse_update_matrix_impl.h#L88)):*
<details><summary><i>Previously, wliue (Wei Liu) wrote…</i></summary><blockquote>

The meaning of hashing might be ambiguous. Could specify that random_seed is used during row selection after a column is matched. 
</blockquote></details>

Done.
___
*[src/main/cc/wfa/virtual_people/core/model/attributes_updater/sparse_update_matrix_impl.cc, line 103 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/9#-McFNcbO9RWN4uf226Wv:-McI9Sff5EVQA92_NQFh:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-core-serving/blob/e8c0d07085a1eb9c49fb396cd1ab50a5a95b4ed6/src/main/cc/wfa/virtual_people/core/model/attributes_updater/sparse_update_matrix_impl.cc#L103)):*
<details><summary><i>Previously, wliue (Wei Liu) wrote…</i></summary><blockquote>

Could check NULL.
</blockquote></details>

Done.
___
*[src/main/cc/wfa/virtual_people/core/model/attributes_updater/sparse_update_matrix_impl.cc, line 106 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/9#-McFNeKz8Qx-lpByr_VV:-McI9TTk9Wl0iGjSpCSe:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-core-serving/blob/e8c0d07085a1eb9c49fb396cd1ab50a5a95b4ed6/src/main/cc/wfa/virtual_people/core/model/attributes_updater/sparse_update_matrix_impl.cc#L106)):*
<details><summary><i>Previously, wliue (Wei Liu) wrote…</i></summary><blockquote>

Could check NULL.
</blockquote></details>

Done.
___
*[src/main/cc/wfa/virtual_people/core/model/attributes_updater/sparse_update_matrix_impl_test.cc, line 159 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/9#-McFObrH-5r8H1p51cqm:-McI9Xqr0p0F5Nx58X2s:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-core-serving/blob/e8c0d07085a1eb9c49fb396cd1ab50a5a95b4ed6/src/main/cc/wfa/virtual_people/core/model/attributes_updater/sparse_update_matrix_impl_test.cc#L159)):*
<details><summary><i>Previously, wliue (Wei Liu) wrote…</i></summary><blockquote>

The probability normalization is done internally, correct? Could add a test that prob doesn't sum to 1.
</blockquote></details>

Done.
___
*[src/main/cc/wfa/virtual_people/core/model/attributes_updater/sparse_update_matrix_impl_test.cc, line 308 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/9#-McFP3Ni6SrFoBaL8K8e:-McI9ZGxCiD7l7yevf_s:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-core-serving/blob/e8c0d07085a1eb9c49fb396cd1ab50a5a95b4ed6/src/main/cc/wfa/virtual_people/core/model/attributes_updater/sparse_update_matrix_impl_test.cc#L308)):*
<details><summary><i>Previously, wliue (Wei Liu) wrote…</i></summary><blockquote>

Could add a comment.
</blockquote></details>

Done.
___
*[src/main/cc/wfa/virtual_people/core/model/utils/update_matrix_helper.h, line 38 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/9#-McFQsdI6y6sNydm0bjj:-McI9b-E07sllWviDRfE:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-core-serving/blob/e8c0d07085a1eb9c49fb396cd1ab50a5a95b4ed6/src/main/cc/wfa/virtual_people/core/model/utils/update_matrix_helper.h#L38)):*
<details><summary><i>Previously, wliue (Wei Liu) wrote…</i></summary><blockquote>

Refer to the constant kNoMatchingIndex.
</blockquote></details>

Done.
___
*[src/main/cc/wfa/virtual_people/core/model/utils/update_matrix_helper.cc, line 28 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/9#-McFRZoY6moSAb5x4rpy:-McGYEDN3Nh1COeRkCm2:b-55x74c) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-core-serving/blob/e8c0d07085a1eb9c49fb396cd1ab50a5a95b4ed6/src/main/cc/wfa/virtual_people/core/model/utils/update_matrix_helper.cc#L28)):*
<details><summary><i>Previously, wliue (Wei Liu) wrote…</i></summary><blockquote>

Add a unit test.
</blockquote></details>

I think it is not necessary to have a standalone unit test, as the behavior heavily depends on the input matchers and hashings, and is already tested by the unit tests of UpdateMatrix and SparseUpdateMatrix.

**Review by wliue — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/9)* status: 4 of 10 files reviewed, 9 unresolved discussions (waiting on @efoxepstein, @EvgSkv, @kunyuchen, @lenjoy, @mpatel24, @my2457, @oliver-amzn, @tcsnfkx, and @wliue)

___
*[src/main/cc/wfa/virtual_people/core/model/attributes_updater/sparse_update_matrix_impl.h, line 29 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/9#-McK8RP_33pkAkz--Cbr:-McK8RP_33pkAkz--Cbs:b-bg5gvm) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-core-serving/blob/c83a48e5da22b116eaca442a50eee22e15db86ef/src/main/cc/wfa/virtual_people/core/model/attributes_updater/sparse_update_matrix_impl.h#L29)):*
> ```objc
> namespace wfa_virtual_people {
> 
> // An representation of update matrix, which only contains the entries that the
> ```

An -> A.
___
*[src/main/cc/wfa/virtual_people/core/model/utils/update_matrix_helper.cc, line 28 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/9#-McFRZoY6moSAb5x4rpy:-McKAQN67Egkj6BwNvj8:b4pcv2g) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-core-serving/blob/e8c0d07085a1eb9c49fb396cd1ab50a5a95b4ed6/src/main/cc/wfa/virtual_people/core/model/utils/update_matrix_helper.cc#L28)):*
<details><summary><i>Previously, tcsnfkx wrote…</i></summary><blockquote>

I think it is not necessary to have a standalone unit test, as the behavior heavily depends on the input matchers and hashings, and is already tested by the unit tests of UpdateMatrix and SparseUpdateMatrix.
</blockquote></details>

Even then, it is worthwhile to have its own tests. For example: both matchers are NULL, both matchers are set, and some simple success case.

**Review by wliue — COMMENTED** [review]
> Reviewed 6 of 6 files at r2.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/9)* status: all files reviewed, 9 unresolved discussions (waiting on @efoxepstein, @EvgSkv, @kunyuchen, @lenjoy, @mpatel24, @my2457, @oliver-amzn, @tcsnfkx, and @wliue)

**Review by efoxepstein — CHANGES_REQUESTED** [review]
> Reviewed 4 of 10 files at r1, 6 of 6 files at r2.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/9)* status: all files reviewed, 13 unresolved discussions (waiting on @EvgSkv, @kunyuchen, @lenjoy, @mpatel24, @my2457, @oliver-amzn, @tcsnfkx, and @wliue)

___
*[src/main/cc/wfa/virtual_people/core/model/attributes_updater/sparse_update_matrix_impl.cc, line 133 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/9#-McKjJi60SSN-Y40wJl_:-McKjJi60SSN-Y40wJla:b-q959ge) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-core-serving/blob/c83a48e5da22b116eaca442a50eee22e15db86ef/src/main/cc/wfa/virtual_people/core/model/attributes_updater/sparse_update_matrix_impl.cc#L133)):*
> ```cpp
> 
>     // Gets the rows.
>     rows.push_back(std::vector<LabelerEvent>(
> ```

Out of curiosity, does `rows.emplace_back(column.rows().begin(), column.rows().end())` work? I would expect it to and it should be a little simpler to read.
___
*[src/main/cc/wfa/virtual_people/core/model/attributes_updater/sparse_update_matrix_impl.cc, line 161 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/9#-McKjUzL4sRkVZZ1hYtb:-McKjUzL4sRkVZZ1hYtc:b-cqvazk) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-core-serving/blob/c83a48e5da22b116eaca442a50eee22e15db86ef/src/main/cc/wfa/virtual_people/core/model/attributes_updater/sparse_update_matrix_impl.cc#L161)):*
> ```cpp
>     }
>   }
>   event.MergeFrom(rows_[indexes.column_index][indexes.row_index]);
> ```

Bounds checks here?
___
*[src/main/cc/wfa/virtual_people/core/model/attributes_updater/update_matrix_impl.cc, line 128 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/9#-McKjg11BqqQM7iFvciW:-McKjg11BqqQM7iFvciX:bmdg4py) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-core-serving/blob/c83a48e5da22b116eaca442a50eee22e15db86ef/src/main/cc/wfa/virtual_people/core/model/attributes_updater/update_matrix_impl.cc#L128)):*
> ```cpp
>     }
>   }
>   event.MergeFrom(rows_[indexes.row_index]);
> ```

Bounds check please.
___
*[src/main/cc/wfa/virtual_people/core/model/utils/update_matrix_helper.cc, line 46 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/9#-McKjpno1QK4om0Yxhiw:-McKjpno1QK4om0Yxhix:begwnrc) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-core-serving/blob/c83a48e5da22b116eaca442a50eee22e15db86ef/src/main/cc/wfa/virtual_people/core/model/utils/update_matrix_helper.cc#L46)):*
> ```cpp
>     return MatrixIndexes({kNoMatchingIndex, kNoMatchingIndex});
>   }
>   int row_index = row_hashings[column_index]->Hash(
> ```

Bounds check please

**Review by tcsnfkx — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/9)* status: 5 of 11 files reviewed, 13 unresolved discussions (waiting on @efoxepstein, @EvgSkv, @kunyuchen, @lenjoy, @mpatel24, @my2457, @oliver-amzn, and @wliue)

___
*[src/main/cc/wfa/virtual_people/core/model/attributes_updater/sparse_update_matrix_impl.h, line 29 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/9#-McK8RP_33pkAkz--Cbr:-McMT5rlB7RICj0ps3Xg:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-core-serving/blob/c83a48e5da22b116eaca442a50eee22e15db86ef/src/main/cc/wfa/virtual_people/core/model/attributes_updater/sparse_update_matrix_impl.h#L29)):*
<details><summary><i>Previously, wliue (Wei Liu) wrote…</i></summary><blockquote>

An -> A.
</blockquote></details>

Done.
___
*[src/main/cc/wfa/virtual_people/core/model/attributes_updater/sparse_update_matrix_impl.cc, line 133 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/9#-McKjJi60SSN-Y40wJl_:-McMT7ov0IV1OJegkxuy:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-core-serving/blob/c83a48e5da22b116eaca442a50eee22e15db86ef/src/main/cc/wfa/virtual_people/core/model/attributes_updater/sparse_update_matrix_impl.cc#L133)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Out of curiosity, does `rows.emplace_back(column.rows().begin(), column.rows().end())` work? I would expect it to and it should be a little simpler to read.
</blockquote></details>

Done.
___
*[src/main/cc/wfa/virtual_people/core/model/attributes_updater/sparse_update_matrix_impl.cc, line 161 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/9#-McKjUzL4sRkVZZ1hYtb:-McMT8cR89F7C0B5v6T8:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-core-serving/blob/c83a48e5da22b116eaca442a50eee22e15db86ef/src/main/cc/wfa/virtual_people/core/model/attributes_updater/sparse_update_matrix_impl.cc#L161)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Bounds checks here?
</blockquote></details>

Done.
___
*[src/main/cc/wfa/virtual_people/core/model/attributes_updater/update_matrix_impl.cc, line 128 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/9#-McKjg11BqqQM7iFvciW:-McMT9O-2Ike0BCZaqG9:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-core-serving/blob/c83a48e5da22b116eaca442a50eee22e15db86ef/src/main/cc/wfa/virtual_people/core/model/attributes_updater/update_matrix_impl.cc#L128)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Bounds check please.
</blockquote></details>

Done.
___
*[src/main/cc/wfa/virtual_people/core/model/utils/update_matrix_helper.cc, line 28 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/9#-McFRZoY6moSAb5x4rpy:-McMTB9n3DKgKSrl3TW5:bamnzir) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-core-serving/blob/e8c0d07085a1eb9c49fb396cd1ab50a5a95b4ed6/src/main/cc/wfa/virtual_people/core/model/utils/update_matrix_helper.cc#L28)):*
<details><summary><i>Previously, wliue (Wei Liu) wrote…</i></summary><blockquote>

Even then, it is worthwhile to have its own tests. For example: both matchers are NULL, both matchers are set, and some simple success case.
</blockquote></details>

Added a test for NULL matchers. The other cases are covered by tests of UpdateMatrix and SparseUpdateMatrix, and  the initialization of the parameters heavily relies on the initialization of UpdateMatrix or SparseUpdateMatrix.
___
*[src/main/cc/wfa/virtual_people/core/model/utils/update_matrix_helper.cc, line 46 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/9#-McKjpno1QK4om0Yxhiw:-McMTAc17SI3RpdufT31:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-core-serving/blob/c83a48e5da22b116eaca442a50eee22e15db86ef/src/main/cc/wfa/virtual_people/core/model/utils/update_matrix_helper.cc#L46)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Bounds check please
</blockquote></details>

Done.

**Review by efoxepstein — APPROVED** [review]
> Reviewed 6 of 6 files at r3.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/9)* status: all files reviewed, 9 unresolved discussions (waiting on @EvgSkv, @kunyuchen, @lenjoy, @mpatel24, @my2457, @oliver-amzn, and @wliue)

**Review by wliue — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/9)* status: all files reviewed, 10 unresolved discussions (waiting on @EvgSkv, @kunyuchen, @lenjoy, @mpatel24, @my2457, @oliver-amzn, @tcsnfkx, and @wliue)

___
*[src/main/cc/wfa/virtual_people/core/model/attributes_updater/update_matrix_impl.cc, line 120 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/9#-McNJWms7W12RWm5Ne0O:-McNJWms7W12RWm5Ne0P:bze6e13) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-core-serving/blob/b8de4ac7934a663d794497f4f306fcffde173e42/src/main/cc/wfa/virtual_people/core/model/attributes_updater/update_matrix_impl.cc#L120)):*
> ```cpp
>           hash_matcher_.get(), filters_matcher_.get(), row_hashings_,
>           random_seed_, event));
>   int row_index = indexes.row_index;
> ```

Nit: move this down to right before it is used.

**Review by mpatel24 — APPROVED** [review]

**Review by efoxepstein — APPROVED** [review]
> Reviewed 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/9)* status: all files reviewed, 9 unresolved discussions (waiting on @EvgSkv, @kunyuchen, @lenjoy, @my2457, @oliver-amzn, and @wliue)

**Review by wliue — APPROVED** [review]
> Reviewed 5 of 6 files at r3, 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/9)* status: all files reviewed, 9 unresolved discussions (waiting on @EvgSkv, @kunyuchen, @lenjoy, @my2457, @oliver-amzn, and @wliue)

**Pull request merged**
