### PR TITLE
Inital commit for supporting Kotlin development

### PR DESCRIPTION
**Pull request by wangyaopw**
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/52)

### CODE REVIEW

**Review by tcsnfkx — DISMISSED** [review]
> Reviewed 3 of 13 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/52)* status: 3 of 13 files reviewed, 1 unresolved discussion (waiting on @wangyaopw and @wliue)

___
*[`src/main/kotlin/org/wfanet/virtualpeople/core/labeler/BUILD.bazel` line 0 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/52#-NB0giLd6Yp2YsTnbk8L:-NB0giLe8MmAkSciuEvs:bz7evw6) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-core-serving/blob/f3694b2d9b1d564c2a1057725b417437082b1612/src/main/kotlin/org/wfanet/virtualpeople/core/labeler/BUILD.bazel#L0)):*
Is it a convention that the directory names have no underscore in Kotlin code?

**Review by wangyaopw — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/52)* status: 3 of 13 files reviewed, 1 unresolved discussion (waiting on @tcsnfkx and @wliue)

___
*[`src/main/kotlin/org/wfanet/virtualpeople/core/labeler/BUILD.bazel` line  at r1](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/52#-NB0giLd6Yp2YsTnbk8L:-NB0pLyMC9yQ7ZrUEZ3Z:b-vl8cc5) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-core-serving/blob/f3694b2d9b1d564c2a1057725b417437082b1612/src/main/kotlin/org/wfanet/virtualpeople/core/labeler/BUILD.bazel#L)):*
<details><summary><i>Previously, tcsnfkx wrote…</i></summary><blockquote>

Is it a convention that the directory names have no underscore in Kotlin code?
</blockquote></details>

yes

https://kotlinlang.org/docs/coding-conventions.html#naming-rules

```
Names of packages are always lowercase and do not use underscores (org.example.project). Using multi-word names is generally discouraged, but if you do need to use multiple words, you can either just concatenate them together or use camel case (org.example.myProject).
```

we have examples like
https://github.com/world-federation-of-advertisers/cross-media-measurement/tree/main/src/main/kotlin/org/wfanet/measurement/eventdataprovider/privacybudgetmanagement

**Comment by tcsnfkx** [comment]
*[`build/repositories.bzl` line 16 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/52#-NBLWHbgAkOBAjsj5ZK1:-NBLWHbhAbJspYRBiahM:bkqapxx) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-core-serving/blob/fc8d9ae12a85c33ab5876ac3e969d931997d4081/build/repositories.bzl#L16)):*
> ```Starlark
> 
> """
> Adds external repos necessary for virtual_people_common.
> ```

Could you please update the comment?

**Review by tcsnfkx — COMMENTED** [review]
> Reviewed 8 of 13 files at r1.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/52)* status: 11 of 13 files reviewed, 1 unresolved discussion (waiting on @SanjayVas, @wangyaopw, and @wliue)

**Review by wangyaopw — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/52)* status: 11 of 13 files reviewed, 1 unresolved discussion (waiting on @SanjayVas, @tcsnfkx, and @wliue)

___
*[`build/repositories.bzl` line 16 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/52#-NBLWHbgAkOBAjsj5ZK1:-NBNaUIm4DBXUHdTjin_:bwwftn3) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-core-serving/blob/fc8d9ae12a85c33ab5876ac3e969d931997d4081/build/repositories.bzl#L16)):*
<details><summary><i>Previously, tcsnfkx wrote…</i></summary><blockquote>

Could you please update the comment?
</blockquote></details>

Done.

nit: such comment could be non-blocking

**Review by wliue — APPROVED** [review]
> Reviewed 12 of 13 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/52)* status: all files reviewed, 1 unresolved discussion (waiting on @SanjayVas and @tcsnfkx)

**Review by wliue — APPROVED** [review]
> Dismissed @tcsnfkx from a discussion.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/52)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @SanjayVas and @tcsnfkx)

**Review by SanjayVas — APPROVED** [review]
> Reviewed 12 of 13 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/52)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @tcsnfkx)

**Pull request merged**
