### PR TITLE
Implement geometric shredding in C++.

### PR DESCRIPTION
**Pull request by tcsnfkx**

### CODE REVIEW

**Review by wliue — CHANGES_REQUESTED** [review]
> Reviewed 7 of 12 files at r1, 5 of 5 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/74)* status: all files reviewed, 12 unresolved discussions (waiting on @EvgSkv, @Marco-Premier, @stevenwarejones, @tcsnfkx, and @wangyaopw)

___
*[`src/main/cc/wfa/virtual_people/core/model/geometric_shredder_impl.h` line 36 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/74#-NZbsTni37bzLA3hLS4y:-NZbsTni37bzLA3hLS4z:b21psy8) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-core-serving/blob/4ecc3f9c81554c369b7a6f3b79498e7cdf77efa1/src/main/cc/wfa/virtual_people/core/model/geometric_shredder_impl.h#L36)):*
> ```objc
> // the geometric shredding parameter psi, and the random seed.
> // The details can be found in the Colab
> // https://colab.sandbox.google.com/drive/11C3CWcldUCrkZxUKvTkzhoxkocgKoP6k
> ```

Change the link to https://github.com/world-federation-of-advertisers/virtual_people_examples/blob/main/notebooks/Geometric_Shredding.ipynb



_Code quote:_
```objc
// https://colab.sandbox.google.com/drive/11C3CWcldUCrkZxUKvTkzhoxkocgKoP6k
```
___
*[`src/main/cc/wfa/virtual_people/core/model/geometric_shredder_impl.h` line 83 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/74#-NZbuiT4CXZaQFS-c5yg:-NZbuiT4CXZaQFS-c5yh:b-qg4blq) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-core-serving/blob/4ecc3f9c81554c369b7a6f3b79498e7cdf77efa1/src/main/cc/wfa/virtual_people/core/model/geometric_shredder_impl.h#L83)):*
> ```objc
>   // the shred value.
>   std::vector<const google::protobuf::FieldDescriptor*> target_field_;
>   // The seed used in hashing during row selection after a column is matched.
> ```

Seems wrong. Update the comment.



_Code quote:_
```objc
  // The seed used in hashing during row selection after a column is matched.
```
___
*[`src/main/cc/wfa/virtual_people/core/model/geometric_shredder_impl.cc` line 111 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/74#-NZc1Z4D3IoNFHm9mNB2:-NZc1Z4D3IoNFHm9mNB3:bs3ynmd) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-core-serving/blob/4ecc3f9c81554c369b7a6f3b79498e7cdf77efa1/src/main/cc/wfa/virtual_people/core/model/geometric_shredder_impl.cc#L111)):*
> ```cpp
>   uint64_t randomness_value = randomness_field_value.value;
> 
>   // Certain shredding.
> ```

@EvgSkv @tcsnfkx 
Does "certain shredding" mean that the field will always be updated? Then maybe also need to check randomness_value != 0. Though in practice it probably doesn't matter.



_Code quote:_
```cpp
  // Certain shredding.
```
___
*[`src/main/cc/wfa/virtual_people/core/model/utils/hash.h` line 27 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/74#-NZc-CE2BzU47pDrY6Kf:-NZc-CE2BzU47pDrY6Kg:b-of45fj) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-core-serving/blob/4ecc3f9c81554c369b7a6f3b79498e7cdf77efa1/src/main/cc/wfa/virtual_people/core/model/utils/hash.h#L27)):*
> ```objc
> double FloatHash(absl::string_view seed);
> 
> // Exponentially distributed hash.
> ```

Could give more details, e.g. the distribution or the formula.



_Code quote:_
```objc
// Exponentially distributed hash.
```
___
*[`src/test/cc/wfa/virtual_people/core/model/geometric_shredder_impl_test.cc` line 53 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/74#-NZc-xF1Bufo_e_93cfo:-NZc-xF1Bufo_e_93cfp:b5ab2u3) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-core-serving/blob/4ecc3f9c81554c369b7a6f3b79498e7cdf77efa1/src/test/cc/wfa/virtual_people/core/model/geometric_shredder_impl_test.cc#L53)):*
> ```cpp
>       &config));
>   EXPECT_THAT(AttributesUpdaterInterface::Build(config).status(),
>               StatusIs(absl::StatusCode::kInvalidArgument, ""));
> ```

Could check error message.



_Code quote:_
```cpp
absl::StatusCode::kInvalidArgument, ""
```
___
*[`src/test/cc/wfa/virtual_people/core/model/geometric_shredder_impl_test.cc` line 69 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/74#-NZc01wHDijesjYykCxE:-NZc01wHDijesjYykCxF:b5ab2u3) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-core-serving/blob/4ecc3f9c81554c369b7a6f3b79498e7cdf77efa1/src/test/cc/wfa/virtual_people/core/model/geometric_shredder_impl_test.cc#L69)):*
> ```cpp
>       &config));
>   EXPECT_THAT(AttributesUpdaterInterface::Build(config).status(),
>               StatusIs(absl::StatusCode::kInvalidArgument, ""));
> ```

Could check error message.



_Code quote:_
```cpp
""
```
___
*[`src/test/cc/wfa/virtual_people/core/model/geometric_shredder_impl_test.cc` line 85 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/74#-NZc04frBzXLwG4KM3k6:-NZc04frBzXLwG4KM3k7:b5ab2u3) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-core-serving/blob/4ecc3f9c81554c369b7a6f3b79498e7cdf77efa1/src/test/cc/wfa/virtual_people/core/model/geometric_shredder_impl_test.cc#L85)):*
> ```cpp
>       &config));
>   EXPECT_THAT(AttributesUpdaterInterface::Build(config).status(),
>               StatusIs(absl::StatusCode::kInvalidArgument, ""));
> ```

Could check error message.
___
*[`src/test/cc/wfa/virtual_people/core/model/geometric_shredder_impl_test.cc` line 101 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/74#-NZc0ABz-WBuGJPg9iyQ:-NZc0ABz-WBuGJPg9iyR:b5ab2u3) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-core-serving/blob/4ecc3f9c81554c369b7a6f3b79498e7cdf77efa1/src/test/cc/wfa/virtual_people/core/model/geometric_shredder_impl_test.cc#L101)):*
> ```cpp
>       &config));
>   EXPECT_THAT(AttributesUpdaterInterface::Build(config).status(),
>               StatusIs(absl::StatusCode::kInvalidArgument, ""));
> ```

Could check error message.



_Code quote:_
```cpp
""
```
___
*[`src/test/cc/wfa/virtual_people/core/model/geometric_shredder_impl_test.cc` line 117 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/74#-NZc0Cul5ZZLFmhkU3_q:-NZc0Cul5ZZLFmhkU3_r:b5ab2u3) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-core-serving/blob/4ecc3f9c81554c369b7a6f3b79498e7cdf77efa1/src/test/cc/wfa/virtual_people/core/model/geometric_shredder_impl_test.cc#L117)):*
> ```cpp
>       &config));
>   EXPECT_THAT(AttributesUpdaterInterface::Build(config).status(),
>               StatusIs(absl::StatusCode::kInvalidArgument, ""));
> ```

Could check error message.



_Code quote:_
```cpp
""
```
___
*[`src/test/cc/wfa/virtual_people/core/model/geometric_shredder_impl_test.cc` line 133 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/74#-NZc0F2HCiVhyfvpKHxG:-NZc0F2I4CAEfxfzyED3:b5ab2u3) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-core-serving/blob/4ecc3f9c81554c369b7a6f3b79498e7cdf77efa1/src/test/cc/wfa/virtual_people/core/model/geometric_shredder_impl_test.cc#L133)):*
> ```cpp
>       &config));
>   EXPECT_THAT(AttributesUpdaterInterface::Build(config).status(),
>               StatusIs(absl::StatusCode::kInvalidArgument, ""));
> ```

Could check error message.



_Code quote:_
```cpp
""
```
___
*[`src/test/cc/wfa/virtual_people/core/model/geometric_shredder_impl_test.cc` line 154 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/74#-NZc0HKm-hGonFhtTMuH:-NZc0HKm-hGonFhtTMuI:b5ab2u3) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-core-serving/blob/4ecc3f9c81554c369b7a6f3b79498e7cdf77efa1/src/test/cc/wfa/virtual_people/core/model/geometric_shredder_impl_test.cc#L154)):*
> ```cpp
>   event.set_acting_fingerprint(1);
>   EXPECT_THAT(updater->Update(event),
>               StatusIs(absl::StatusCode::kInvalidArgument, ""));
> ```

Could check error message.



_Code quote:_
```cpp
""
```
___
*[`src/test/cc/wfa/virtual_people/core/model/geometric_shredder_impl_test.cc` line 175 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/74#-NZc0JEMAvJWdex-aRny:-NZc0JEMAvJWdex-aRnz:b5ab2u3) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-core-serving/blob/4ecc3f9c81554c369b7a6f3b79498e7cdf77efa1/src/test/cc/wfa/virtual_people/core/model/geometric_shredder_impl_test.cc#L175)):*
> ```cpp
>   event.mutable_labeler_input()->mutable_event_id()->set_id_fingerprint(1);
>   EXPECT_THAT(updater->Update(event),
>               StatusIs(absl::StatusCode::kInvalidArgument, ""));
> ```

Could check error message.



_Code quote:_
```cpp
""
```

**Review by EvgSkv — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/74#-:-NZgRgcaA0UcMgokmUJ4:bnfp4nl)* status: all files reviewed, 12 unresolved discussions (waiting on @Marco-Premier, @stevenwarejones, @tcsnfkx, and @wangyaopw)

**Review by stevenwarejones — APPROVED** [review]
> Reviewed 5 of 12 files at r1, 3 of 5 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/74)* status: all files reviewed, 12 unresolved discussions (waiting on @Marco-Premier, @tcsnfkx, @wangyaopw, and @wliue)

___
*[`src/test/cc/wfa/virtual_people/core/model/geometric_shredder_impl_test.cc` line 53 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/74#-NZc-xF1Bufo_e_93cfo:-N_-HYyC43zRuzQPgHBV:b-xu6t46) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-core-serving/blob/4ecc3f9c81554c369b7a6f3b79498e7cdf77efa1/src/test/cc/wfa/virtual_people/core/model/geometric_shredder_impl_test.cc#L53)):*
<details><summary><i>Previously, wliue (Wei Liu) wrote…</i></summary><blockquote>

Could check error message.
</blockquote></details>

I don't believe its a best practice to check the error message, itself, just that the error type is correct.

**Review by tcsnfkx — COMMENTED** [review]
> Dismissed @wliue from 12 discussions.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/74)* status: 9 of 12 files reviewed, all discussions resolved (waiting on @Marco-Premier, @stevenwarejones, @wangyaopw, and @wliue)

___
*[`src/main/cc/wfa/virtual_people/core/model/geometric_shredder_impl.h` line 36 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/74#-NZbsTni37bzLA3hLS4y:-NZdYCQX7mEROTJmqsYc:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-core-serving/blob/4ecc3f9c81554c369b7a6f3b79498e7cdf77efa1/src/main/cc/wfa/virtual_people/core/model/geometric_shredder_impl.h#L36)):*
<details><summary><i>Previously, wliue (Wei Liu) wrote…</i></summary><blockquote>

Change the link to https://github.com/world-federation-of-advertisers/virtual_people_examples/blob/main/notebooks/Geometric_Shredding.ipynb
</blockquote></details>

Done.
___
*[`src/main/cc/wfa/virtual_people/core/model/geometric_shredder_impl.h` line 83 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/74#-NZbuiT4CXZaQFS-c5yg:-NZdYSyW66eXbA3QWtpJ:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-core-serving/blob/4ecc3f9c81554c369b7a6f3b79498e7cdf77efa1/src/main/cc/wfa/virtual_people/core/model/geometric_shredder_impl.h#L83)):*
<details><summary><i>Previously, wliue (Wei Liu) wrote…</i></summary><blockquote>

Seems wrong. Update the comment.
</blockquote></details>

Done.
___
*[`src/main/cc/wfa/virtual_people/core/model/geometric_shredder_impl.cc` line 111 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/74#-NZc1Z4D3IoNFHm9mNB2:-N_5CN1mBoQ50hID7saQ:b-s0xyx2) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-core-serving/blob/4ecc3f9c81554c369b7a6f3b79498e7cdf77efa1/src/main/cc/wfa/virtual_people/core/model/geometric_shredder_impl.cc#L111)):*
<details><summary><i>Previously, wliue (Wei Liu) wrote…</i></summary><blockquote>

@EvgSkv @tcsnfkx 
Does "certain shredding" mean that the field will always be updated? Then maybe also need to check randomness_value != 0. Though in practice it probably doesn't matter.
</blockquote></details>

Comments updated.
___
*[`src/main/cc/wfa/virtual_people/core/model/utils/hash.h` line 27 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/74#-NZc-CE2BzU47pDrY6Kf:-N_5AjjG0wwqxZ0GfaNF:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-core-serving/blob/4ecc3f9c81554c369b7a6f3b79498e7cdf77efa1/src/main/cc/wfa/virtual_people/core/model/utils/hash.h#L27)):*
<details><summary><i>Previously, wliue (Wei Liu) wrote…</i></summary><blockquote>

Could give more details, e.g. the distribution or the formula.
</blockquote></details>

Done.
___
*[`src/test/cc/wfa/virtual_people/core/model/geometric_shredder_impl_test.cc` line 53 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/74#-NZc-xF1Bufo_e_93cfo:-N_5AvVL3yYHCVTGl8EF:b5qv0ec) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-core-serving/blob/4ecc3f9c81554c369b7a6f3b79498e7cdf77efa1/src/test/cc/wfa/virtual_people/core/model/geometric_shredder_impl_test.cc#L53)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

I don't believe its a best practice to check the error message, itself, just that the error type is correct.
</blockquote></details>

I agree that we should check we catch the error, but not check the error message.
___
*[`src/test/cc/wfa/virtual_people/core/model/geometric_shredder_impl_test.cc` line 69 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/74#-NZc01wHDijesjYykCxE:-N_5Bq-VEBGTAX2_vTsP:b2nreh6) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-core-serving/blob/4ecc3f9c81554c369b7a6f3b79498e7cdf77efa1/src/test/cc/wfa/virtual_people/core/model/geometric_shredder_impl_test.cc#L69)):*
<details><summary><i>Previously, wliue (Wei Liu) wrote…</i></summary><blockquote>

Could check error message.
</blockquote></details>

Same as above.
___
*[`src/test/cc/wfa/virtual_people/core/model/geometric_shredder_impl_test.cc` line 85 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/74#-NZc04frBzXLwG4KM3k6:-N_5BtaL7ErNzpv_vsnt:b2nreh6) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-core-serving/blob/4ecc3f9c81554c369b7a6f3b79498e7cdf77efa1/src/test/cc/wfa/virtual_people/core/model/geometric_shredder_impl_test.cc#L85)):*
<details><summary><i>Previously, wliue (Wei Liu) wrote…</i></summary><blockquote>

Could check error message.
</blockquote></details>

Same as above.
___
*[`src/test/cc/wfa/virtual_people/core/model/geometric_shredder_impl_test.cc` line 101 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/74#-NZc0ABz-WBuGJPg9iyQ:-N_5BuKI5SpRqn3z9ZcM:b2nreh6) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-core-serving/blob/4ecc3f9c81554c369b7a6f3b79498e7cdf77efa1/src/test/cc/wfa/virtual_people/core/model/geometric_shredder_impl_test.cc#L101)):*
<details><summary><i>Previously, wliue (Wei Liu) wrote…</i></summary><blockquote>

Could check error message.
</blockquote></details>

Same as above.
___
*[`src/test/cc/wfa/virtual_people/core/model/geometric_shredder_impl_test.cc` line 117 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/74#-NZc0Cul5ZZLFmhkU3_q:-N_5Busd94UgoOu3y0RD:b2nreh6) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-core-serving/blob/4ecc3f9c81554c369b7a6f3b79498e7cdf77efa1/src/test/cc/wfa/virtual_people/core/model/geometric_shredder_impl_test.cc#L117)):*
<details><summary><i>Previously, wliue (Wei Liu) wrote…</i></summary><blockquote>

Could check error message.
</blockquote></details>

Same as above.
___
*[`src/test/cc/wfa/virtual_people/core/model/geometric_shredder_impl_test.cc` line 133 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/74#-NZc0F2HCiVhyfvpKHxG:-N_5BvLW02aUKc_n9I-h:b2nreh6) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-core-serving/blob/4ecc3f9c81554c369b7a6f3b79498e7cdf77efa1/src/test/cc/wfa/virtual_people/core/model/geometric_shredder_impl_test.cc#L133)):*
<details><summary><i>Previously, wliue (Wei Liu) wrote…</i></summary><blockquote>

Could check error message.
</blockquote></details>

Same as above.
___
*[`src/test/cc/wfa/virtual_people/core/model/geometric_shredder_impl_test.cc` line 154 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/74#-NZc0HKm-hGonFhtTMuH:-N_5BvqL1bMDlAD4bKau:b2nreh6) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-core-serving/blob/4ecc3f9c81554c369b7a6f3b79498e7cdf77efa1/src/test/cc/wfa/virtual_people/core/model/geometric_shredder_impl_test.cc#L154)):*
<details><summary><i>Previously, wliue (Wei Liu) wrote…</i></summary><blockquote>

Could check error message.
</blockquote></details>

Same as above.
___
*[`src/test/cc/wfa/virtual_people/core/model/geometric_shredder_impl_test.cc` line 175 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/74#-NZc0JEMAvJWdex-aRny:-N_5BwMt4h_4X54gPVJf:b2nreh6) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-core-serving/blob/4ecc3f9c81554c369b7a6f3b79498e7cdf77efa1/src/test/cc/wfa/virtual_people/core/model/geometric_shredder_impl_test.cc#L175)):*
<details><summary><i>Previously, wliue (Wei Liu) wrote…</i></summary><blockquote>

Could check error message.
</blockquote></details>

Same as above.

**Review by wliue — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/74)* status: 9 of 12 files reviewed, all discussions resolved (waiting on @Marco-Premier, @stevenwarejones, and @wangyaopw)

___
*[`src/test/cc/wfa/virtual_people/core/model/geometric_shredder_impl_test.cc` line 53 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/74#-NZc-xF1Bufo_e_93cfo:-N_5E1jO2JbGbM8Kz3wT:babwf1j) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-core-serving/blob/4ecc3f9c81554c369b7a6f3b79498e7cdf77efa1/src/test/cc/wfa/virtual_people/core/model/geometric_shredder_impl_test.cc#L53)):*
<details><summary><i>Previously, tcsnfkx wrote…</i></summary><blockquote>

I agree that we should check we catch the error, but not check the error message.
</blockquote></details>

Note that here all errors returned have the same type kInvalidArgument.
We can check error with regex, not the exact error message. The benefit is to ensure we have the proper test coverage. For example, the test case may be constructed in a way that if fails with the same error type, but not for the correct reason.

**Review by tcsnfkx — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/74)* status: 8 of 12 files reviewed, all discussions resolved (waiting on @Marco-Premier, @stevenwarejones, @wangyaopw, and @wliue)

___
*[`src/test/cc/wfa/virtual_people/core/model/geometric_shredder_impl_test.cc` line 53 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/74#-NZc-xF1Bufo_e_93cfo:-N_6BF0z87ZFPm3FBZAZ:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-core-serving/blob/4ecc3f9c81554c369b7a6f3b79498e7cdf77efa1/src/test/cc/wfa/virtual_people/core/model/geometric_shredder_impl_test.cc#L53)):*
<details><summary><i>Previously, wliue (Wei Liu) wrote…</i></summary><blockquote>

Note that here all errors returned have the same type kInvalidArgument.
We can check error with regex, not the exact error message. The benefit is to ensure we have the proper test coverage. For example, the test case may be constructed in a way that if fails with the same error type, but not for the correct reason. 
</blockquote></details>

Done.

**Review by stevenwarejones — APPROVED** [review]
> Reviewed 1 of 12 files at r1, 1 of 5 files at r2, 3 of 3 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/74)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @Marco-Premier and @wangyaopw)

**Review by wliue — APPROVED** [review]
> Reviewed 3 of 3 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/74)* status: all files reviewed, 1 unresolved discussion (waiting on @Marco-Premier, @tcsnfkx, and @wangyaopw)

___
*[`src/test/cc/wfa/virtual_people/core/model/geometric_shredder_impl_test.cc` line 298 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/74#-N_AEceBE9a7Kk1rdwer:-N_AEceBE9a7Kk1rdwes:bxchrjp) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-core-serving/blob/ca00ca75c1cf9f5e0c284a3a98e763ecefdb2935/src/test/cc/wfa/virtual_people/core/model/geometric_shredder_impl_test.cc#L298)):*
> ```cpp
>     double shred_chance = static_cast<double>(shred_count) /
>                           static_cast<double>(kRandomnessKeyNumber);
>     EXPECT_THAT(shred_chance, DoubleNear(0.65, 0.01));
> ```

This test works fine for testing the functionality. OTOH, the tests are also used to make sure that the Kotlin and C++ implementations behave the same. For that purpose, could you please change this test to compare to the exact value? Could follow the example in https://github.com/world-federation-of-advertisers/virtual-people-core-serving/blob/main/src/test/cc/wfa/virtual_people/core/model/update_matrix_impl_test.cc



_Code quote:_
```cpp
    double shred_chance = static_cast<double>(shred_count) /
                          static_cast<double>(kRandomnessKeyNumber);
    EXPECT_THAT(shred_chance, DoubleNear(0.65, 0.01));
```

**Review by tcsnfkx — COMMENTED** [review]
> Dismissed @wliue from a discussion.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/74)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @Marco-Premier and @wangyaopw)

___
*[`src/test/cc/wfa/virtual_people/core/model/geometric_shredder_impl_test.cc` line 298 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/74#-N_AEceBE9a7Kk1rdwer:-N_B2cIJDODTAluca6Oo:b-grs7l8) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-core-serving/blob/46857f011a15dc27ad26d870ab3f96e89789136b/src/test/cc/wfa/virtual_people/core/model/geometric_shredder_impl_test.cc#L298)):*
<details><summary><i>Previously, wliue (Wei Liu) wrote…</i></summary><blockquote>

This test works fine for testing the functionality. OTOH, the tests are also used to make sure that the Kotlin and C++ implementations behave the same. For that purpose, could you please change this test to compare to the exact value? Could follow the example in https://github.com/world-federation-of-advertisers/virtual-people-core-serving/blob/main/src/test/cc/wfa/virtual_people/core/model/update_matrix_impl_test.cc
</blockquote></details>

To make sure the Kotlin and C++ implementations behave the same, I think we should create protobuf text files as input and expected output, and make both Kotlin and C++ tests to read from the same files. Including the data in the test code makes it easy to change the test data in one side only. I think we can add the tests in future PRs.

**Pull request merged**
