### PR TITLE
Implement the kotlin BranchNodeImpl class.

### PR DESCRIPTION
**Pull request by wangyaopw**
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/65)

### CODE REVIEW

**Review by wliue — CHANGES_REQUESTED** [review]
> Reviewed 11 of 11 files at r1.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/65)* status: 9 of 11 files reviewed, 4 unresolved discussions (waiting on @tcsnfkx, @wangyaopw, and @wliue)

___
*[`src/main/kotlin/org/wfanet/virtualpeople/core/model/BranchNodeImpl.kt` line 33 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/65#-NBx74wk5n6kpcGg7vIE:-NBx74wk5n6kpcGg7vIF:b-hmntbr) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-core-serving/blob/10e04b4f5ff939a8b12c3315cc1ebf6866f95761/src/main/kotlin/org/wfanet/virtualpeople/core/model/BranchNodeImpl.kt#L33)):*
> ```Kotlin
>  * @param hashing if chance is set in each branches in nodeConfig, hashing is set and used to select
>  * a child node with randomSeed when Apply is called.
>  * @param randomSeed a seed used by the hashing
> ```

Nit: end with '.' to be consistent.
___
*[`src/main/kotlin/org/wfanet/virtualpeople/core/model/BranchNodeImpl.kt` line 37 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/65#-NBx7FbP-MgFg9J2raZU:-NBx7FbP-MgFg9J2raZV:bbmyka3) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-core-serving/blob/10e04b4f5ff939a8b12c3315cc1ebf6866f95761/src/main/kotlin/org/wfanet/virtualpeople/core/model/BranchNodeImpl.kt#L37)):*
> ```Kotlin
>  * select the first child node whose condition matches when Apply is called.
>  * @param updaters if updates is set in nodeConfig, updaters is set. When calling Apply, entries of
>  * updaters] is applied to the event in order. Each entry of updaters updates the value of some
> ```

Missing '['?



_Code quote:_
```Kotlin
updaters] 
```
___
*[`src/main/kotlin/org/wfanet/virtualpeople/core/model/BranchNodeImpl.kt` line 91 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/65#-NBy-HQV2Xben6b7Qwa6:-NBy-HQV2Xben6b7Qwa7:b-1ntn4u) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-core-serving/blob/10e04b4f5ff939a8b12c3315cc1ebf6866f95761/src/main/kotlin/org/wfanet/virtualpeople/core/model/BranchNodeImpl.kt#L91)):*
> ```Kotlin
>           event.build().copy { actingFingerprint = cloneFingerprint.toLong() }.toBuilder()
>         setValueToProtoBuilder(clonedEventBuilder, personIndexField, personIndex)
>         clonedEventBuilder
> ```

What is the purpose of this line?
___
*[`src/main/kotlin/org/wfanet/virtualpeople/core/model/BranchNodeImpl.kt` line 132 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/65#-NBy0fynB7Fw5VHfzTja:-NBy0fynB7Fw5VHfzTjb:b-z2ra9v) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-core-serving/blob/10e04b4f5ff939a8b12c3315cc1ebf6866f95761/src/main/kotlin/org/wfanet/virtualpeople/core/model/BranchNodeImpl.kt#L132)):*
> ```Kotlin
>      * At least one of @node_config.branch_node.branches has chance set, and at least one of
>      * 4. [nodeConfig].branch_node.branches has condition set. When node_index is set in
>      * 5. [nodeConfig].branch_node.branches, [nodeRefs] has no entry for this node_index.
> ```

Need to rephrase this comment. Seems it has incorrect formatting.



_Code quote:_
```Kotlin
     * 1. [nodeConfig].branch_node is not set.
     * 2. [nodeConfig].branch_node.branches is empty. There is at least one of
     * 3. [nodeConfig].branch_node.branches, which has neither node_index nor node set. There is at
     * least one of @node_config.branch_node.branches, which has neither chance nor condition set.
     * At least one of @node_config.branch_node.branches has chance set, and at least one of
     * 4. [nodeConfig].branch_node.branches has condition set. When node_index is set in
     * 5. [nodeConfig].branch_node.branches, [nodeRefs] has no entry for this node_index.
```

**Review by wangyaopw — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/65)* status: 9 of 11 files reviewed, 3 unresolved discussions (waiting on @tcsnfkx and @wliue)

___
*[`src/main/kotlin/org/wfanet/virtualpeople/core/model/BranchNodeImpl.kt` line 37 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/65#-NBx7FbP-MgFg9J2raZU:-NBy5qRp7kx7uJrh9N7i:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-core-serving/blob/10e04b4f5ff939a8b12c3315cc1ebf6866f95761/src/main/kotlin/org/wfanet/virtualpeople/core/model/BranchNodeImpl.kt#L37)):*
<details><summary><i>Previously, wliue (Wei Liu) wrote…</i></summary><blockquote>

Missing '['?
</blockquote></details>

Done.
___
*[`src/main/kotlin/org/wfanet/virtualpeople/core/model/BranchNodeImpl.kt` line 91 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/65#-NBy-HQV2Xben6b7Qwa6:-NBy5tsI8-_B8CBqFGVg:byxey9u) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-core-serving/blob/10e04b4f5ff939a8b12c3315cc1ebf6866f95761/src/main/kotlin/org/wfanet/virtualpeople/core/model/BranchNodeImpl.kt#L91)):*
<details><summary><i>Previously, wliue (Wei Liu) wrote…</i></summary><blockquote>

What is the purpose of this line?
</blockquote></details>

to return clonedEventBuilder at the result of this code block.

The object returned by the last line is the return value of the lambda function



_Code quote:_
```Kotlin
clonedEventBuilder
```
___
*[`src/main/kotlin/org/wfanet/virtualpeople/core/model/BranchNodeImpl.kt` line 132 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/65#-NBy0fynB7Fw5VHfzTja:-NBy6ym0-8Kl_va8EJhr:bepk2ll) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-core-serving/blob/10e04b4f5ff939a8b12c3315cc1ebf6866f95761/src/main/kotlin/org/wfanet/virtualpeople/core/model/BranchNodeImpl.kt#L132)):*
<details><summary><i>Previously, wliue (Wei Liu) wrote…</i></summary><blockquote>

Need to rephrase this comment. Seems it has incorrect formatting.
</blockquote></details>

updated two @ node_config to [nodeConfig], the others look good to me.

**Review by wliue — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/65)* status: 8 of 11 files reviewed, 1 unresolved discussion (waiting on @tcsnfkx, @wangyaopw, and @wliue)

___
*[`src/main/kotlin/org/wfanet/virtualpeople/core/model/BranchNodeImpl.kt` line 132 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/65#-NBy0fynB7Fw5VHfzTja:-NBy7rPaBuUP1grWVajb:b-uehoqy) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-core-serving/blob/10e04b4f5ff939a8b12c3315cc1ebf6866f95761/src/main/kotlin/org/wfanet/virtualpeople/core/model/BranchNodeImpl.kt#L132)):*
<details><summary><i>Previously, wangyaopw (Yao Wang) wrote…</i></summary><blockquote>

updated two @ node_config to [nodeConfig], the others look good to me.
</blockquote></details>

This is broken and number-listed at wrong places. Please update to match the c++ comment.

**Review by wangyaopw — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/65)* status: 8 of 11 files reviewed, 1 unresolved discussion (waiting on @tcsnfkx and @wliue)

___
*[`src/main/kotlin/org/wfanet/virtualpeople/core/model/BranchNodeImpl.kt` line 132 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/65#-NBy0fynB7Fw5VHfzTja:-NByA2PJ2F3yKp3S9fru:bde8vtk) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-core-serving/blob/10e04b4f5ff939a8b12c3315cc1ebf6866f95761/src/main/kotlin/org/wfanet/virtualpeople/core/model/BranchNodeImpl.kt#L132)):*
<details><summary><i>Previously, wliue (Wei Liu) wrote…</i></summary><blockquote>

This is broken and number-listed at wrong places. Please update to match the c++ comment.
</blockquote></details>

oops, you are right. Updated.

**Review by wliue — APPROVED** [review]
> Reviewed 2 of 2 files at r2, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/65)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @tcsnfkx)

**Pull request merged**
