### PR TITLE
Add Kotlin implementation of GeometricShredder.

### PR DESCRIPTION
**Pull request by wliue**
Add Kotlin implementation of GeometricShredder.

### CODE REVIEW

**Comment by wfa-reviewable** [comment]
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/77)

**Review by emadlivani — APPROVED** [review]

**Review by Marco-Premier — APPROVED** [review]
> Reviewed 2 of 7 files at r1.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/77)* status: 2 of 7 files reviewed, 1 unresolved discussion (waiting on @stevenwarejones and @wliue)

___
*[`src/main/kotlin/org/wfanet/virtualpeople/core/model/GeometricShredderImpl.kt` line 27 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/77#-OB6dw566g4lxDVn38IU:-OB6dw57E1b7slpq-zqq:br5mwmp) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-core-serving/blob/e882f94bee4fc1ad097259a4ddf6e38cfdb0d78e/src/main/kotlin/org/wfanet/virtualpeople/core/model/GeometricShredderImpl.kt#L27)):*
> ```Kotlin
> import org.wfanet.virtualpeople.common.fieldfilter.utils.getValueFromProto
> import org.wfanet.virtualpeople.common.fieldfilter.utils.setValueToProtoBuilder
> import org.wfanet.virtualpeople.core.model.utils.*
> ```

nit: wildcard imports are not allowed



_Code quote:_
```Kotlin
import org.wfanet.virtualpeople.core.model.utils.*
```

**Review by wliue — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/77)* status: 2 of 7 files reviewed, all discussions resolved (waiting on @stevenwarejones)

___
*[`src/main/kotlin/org/wfanet/virtualpeople/core/model/GeometricShredderImpl.kt` line 27 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/77#-OB6dw566g4lxDVn38IU:-OB77VnNCBgkpWTz0ZW9:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-core-serving/blob/e882f94bee4fc1ad097259a4ddf6e38cfdb0d78e/src/main/kotlin/org/wfanet/virtualpeople/core/model/GeometricShredderImpl.kt#L27)):*
<details><summary><i>Previously, Marco-Premier (marcopremier) wrote…</i></summary><blockquote>

nit: wildcard imports are not allowed
</blockquote></details>

Done.

**Review by emadlivani — APPROVED** [review]
> Reviewed 6 of 7 files at r1, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/77)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @stevenwarejones)

**Pull request merged**
