### PR TITLE
Implement the kotlin Labeler class.

### PR DESCRIPTION
**Pull request by wangyaopw**
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/67)

### CODE REVIEW

**Review by wliue — APPROVED** [review]
> Reviewed 59 of 59 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/67)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @tcsnfkx)

**Review by wliue — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/67)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @tcsnfkx)

**Review by wangyaopw — COMMENTED** [review]
> Reviewed 56 of 59 files at r1, 5 of 5 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/67)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @tcsnfkx)

**Review by wangyaopw — COMMENTED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/67)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @tcsnfkx)

**Pull request merged**
