### PR TITLE
Optimize consistent_hash_test CPU-time from 140s to 9s

### PR DESCRIPTION
**Pull request by efoxepstein**
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/18)

### CODE REVIEW

**Review by wliue — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/18)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @efoxepstein, @mpatel24, and @tcsnfkx)

___
*[src/main/cc/wfa/virtual_people/core/model/utils/consistent_hash_test.cc, line 38 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/18#-MfJVTgu5hi_b_cK2LmI:-MfJVTgu5hi_b_cK2LmJ:bgjania) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-core-serving/blob/c52fe12158c137dcc719b494c27304e6dbfbb305/src/main/cc/wfa/virtual_people/core/model/utils/consistent_hash_test.cc#L38)):*
> ```
>     EXPECT_THAT(output, AnyOf(last_output, num_buckets - 1))
> ```

Is the saving mainly from this change or the random lib?

**Review by efoxepstein — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/18)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @mpatel24, @tcsnfkx, and @wliue)

___
*[src/main/cc/wfa/virtual_people/core/model/utils/consistent_hash_test.cc, line 38 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/18#-MfJVTgu5hi_b_cK2LmI:-MfJWN9gCfPWfmw4Cu0o:b-jubwxq) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-core-serving/blob/c52fe12158c137dcc719b494c27304e6dbfbb305/src/main/cc/wfa/virtual_people/core/model/utils/consistent_hash_test.cc#L38)):*
<details><summary><i>Previously, wliue (Wei Liu) wrote…</i></summary><blockquote>

> ```
>     EXPECT_THAT(output, AnyOf(last_output, num_buckets - 1))
> ```

Is the saving mainly from this change or the random lib?
</blockquote></details>

The speed-up is achieved by moving assertions out of loops (and asserting over whole vectors at once).

The change to absl's random library is for consistency with the rest of the codebase and to fix some lint errors.

**Review by wliue — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/18)* status: 0 of 2 files reviewed, all discussions resolved (waiting on @kunyuchen, @mpatel24, @oliver-amzn, and @tcsnfkx)

**Review by tcsnfkx — APPROVED** [review]
> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/18)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @kunyuchen, @mpatel24, and @oliver-amzn)

**Comment by efoxepstein** [comment]
Closing this PR as it was cherry-picked into https://github.com/world-federation-of-advertisers/virtual-people-core-serving/pull/19.

**Pull request closed without merging**
