### PR TITLE
Implement the kotlin DistributedConsistentHashing

### PR DESCRIPTION
**Pull request by wangyaopw**
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/54)

### CODE REVIEW

**Review by wliue — APPROVED** [review]
> Reviewed 5 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/54)* status: all files reviewed, 1 unresolved discussion (waiting on @tcsnfkx and @wangyaopw)

___
*[`src/main/kotlin/org/wfanet/virtualpeople/core/model/utils/DistributedConsistentHashing.kt` line 82 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/54#-NBTwQNz7Z0Dh8h1q5Vw:-NBTwQNz7Z0Dh8h1q5Vx:bwpritq) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-core-serving/blob/12482596bdc7df713535ebbddc9c31e6ee468fbd/src/main/kotlin/org/wfanet/virtualpeople/core/model/utils/DistributedConsistentHashing.kt#L82)):*
> ```Kotlin
>       /**
>        * FarmHash C++ use uint64 as output type. FarmHash Java use Long as output type. Convert to
>        * ULong to make sure our Kotlin and C++ implementations match each other.
> ```

Is there a test case cover int64 vs uint64?



_Code quote:_
```Kotlin
       * FarmHash C++ use uint64 as output type. FarmHash Java use Long as output type. Convert to
       * ULong to make sure our Kotlin and C++ implementations match each other.
```

**Review by wangyaopw — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/54)* status: all files reviewed, 1 unresolved discussion (waiting on @tcsnfkx and @wliue)

___
*[`src/main/kotlin/org/wfanet/virtualpeople/core/model/utils/DistributedConsistentHashing.kt` line 82 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/54#-NBTwQNz7Z0Dh8h1q5Vw:-NBTzExY0KXJ4eXIm9X1:bp2ey2r) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-core-serving/blob/12482596bdc7df713535ebbddc9c31e6ee468fbd/src/main/kotlin/org/wfanet/virtualpeople/core/model/utils/DistributedConsistentHashing.kt#L82)):*
<details><summary><i>Previously, wliue (Wei Liu) wrote…</i></summary><blockquote>

Is there a test case cover int64 vs uint64?
</blockquote></details>

Not sure what you mean. 

uint64 proto fields are read as Long in kotlin, and so it int64.

For non proto types, we use ULong for uint64 and Long for int64.

So C++ and Kotlin behave the same.

**Review by wliue — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/54)* status: all files reviewed, 1 unresolved discussion (waiting on @tcsnfkx and @wangyaopw)

___
*[`src/main/kotlin/org/wfanet/virtualpeople/core/model/utils/DistributedConsistentHashing.kt` line 82 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/54#-NBTwQNz7Z0Dh8h1q5Vw:-NBU-l6PBCxPQQEZITAy:b-g53qno) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-core-serving/blob/12482596bdc7df713535ebbddc9c31e6ee468fbd/src/main/kotlin/org/wfanet/virtualpeople/core/model/utils/DistributedConsistentHashing.kt#L82)):*
<details><summary><i>Previously, wangyaopw (Yao Wang) wrote…</i></summary><blockquote>

Not sure what you mean. 

uint64 proto fields are read as Long in kotlin, and so it int64.

For non proto types, we use ULong for uint64 and Long for int64.

So C++ and Kotlin behave the same.
</blockquote></details>

I mean a test case that Java FarmHash returns negative value.

**Review by wangyaopw — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/54)* status: all files reviewed, 1 unresolved discussion (waiting on @tcsnfkx and @wliue)

___
*[`src/main/kotlin/org/wfanet/virtualpeople/core/model/utils/DistributedConsistentHashing.kt` line 82 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/54#-NBTwQNz7Z0Dh8h1q5Vw:-NBU1jeREYiFK1Z7Au3R:b-dabdgf) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-core-serving/blob/12482596bdc7df713535ebbddc9c31e6ee468fbd/src/main/kotlin/org/wfanet/virtualpeople/core/model/utils/DistributedConsistentHashing.kt#L82)):*
<details><summary><i>Previously, wliue (Wei Liu) wrote…</i></summary><blockquote>

I mean a test case that Java FarmHash returns negative value. 
</blockquote></details>

We have 10000 random hashes. I assume ~50% of them would be negative. After converted to ULong in `floatHash()`, the result is always equal to the c++ result.



_Code quote:_
```Kotlin
floatHash
```

**Review by wliue — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/54)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @tcsnfkx)

___
*[`src/main/kotlin/org/wfanet/virtualpeople/core/model/utils/DistributedConsistentHashing.kt` line 82 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/54#-NBTwQNz7Z0Dh8h1q5Vw:-NBUBZNP4OUzLHYxIRt6:b-81nlyc) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-core-serving/blob/12482596bdc7df713535ebbddc9c31e6ee468fbd/src/main/kotlin/org/wfanet/virtualpeople/core/model/utils/DistributedConsistentHashing.kt#L82)):*
<details><summary><i>Previously, wangyaopw (Yao Wang) wrote…</i></summary><blockquote>

We have 10000 random hashes. I assume ~50% of them would be negative. After converted to ULong in `floatHash()`, the result is always equal to the c++ result.
</blockquote></details>

SGTM.

**Review by wliue — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/54)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @tcsnfkx)

**Pull request merged**
