### PR TITLE
Migrate deps to common_cpp

### PR DESCRIPTION
**Pull request by enfreck**
Migrate status-macros, matchers, and macros to common_cpp

---
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/19)

### CODE REVIEW

**Review by efoxepstein — APPROVED** [review]
> Reviewed 14 of 31 files at r1.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/19)* status: 14 of 31 files reviewed, 1 unresolved discussion (waiting on @enfreck)

___
*[WORKSPACE, line 29 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/19#-MfJnqTeCc1sXNs8mPMp:-MfJnqTeCc1sXNs8mPMq:b-we9k6i) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-core-serving/blob/12ec4d7d5b8ede032bfd76fd0ce09cd942ba9592/WORKSPACE#L29)):*
> ```Starlark
> 
> new_git_repository(
>     name = "com_google_farmhash",
> ```

Can this be deleted? It should be provided by `common-cpp` (might need to update `@com_google_farmhash` to `@farmhash` if we have a mismatch there.

**Review by efoxepstein — APPROVED** [review]
> Reviewed 17 of 31 files at r1.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/19)* status: all files reviewed, 2 unresolved discussions (waiting on @enfreck, @kunyuchen, @lenjoy, @mpatel24, @oliver-amzn, @tcsnfkx, and @wliue)

___
*[src/main/cc/wfa/virtual_people/core/model/utils/distributed_consistent_hashing.cc, line 71 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/19#-MfJocGI3-OUN73P6BQ4:-MfJocGI3-OUN73P6BQ5:bz7e7xs) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-core-serving/blob/12ec4d7d5b8ede032bfd76fd0ce09cd942ba9592/src/main/cc/wfa/virtual_people/core/model/utils/distributed_consistent_hashing.cc#L71)):*
> ```cpp
> double ComputeXi(absl::string_view random_seed, const int32_t choice,
>                  const double probability) {
>   return (-std::log(FloatHash(GetFullSeed(random_seed, choice))) / probability);
> ```

Can you remove the unnecessary outer parens here please while you're updating this line of code?

**Review by wliue — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/19)* status: all files reviewed, 4 unresolved discussions (waiting on @enfreck, @kunyuchen, @lenjoy, @mpatel24, @oliver-amzn, and @tcsnfkx)

___
*[WORKSPACE, line 42 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/19#-MfJvTWZ2I71wSKF_8U8:-MfJvTWZ2I71wSKF_8U9:bjwv6ph) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-core-serving/blob/12ec4d7d5b8ede032bfd76fd0ce09cd942ba9592/WORKSPACE#L42)):*
> ```Starlark
> 
> git_repository(
>     name = "cross_media_measurement",
> ```

This should be deleted, correct?
___
*[src/main/cc/wfa/virtual_people/core/labeler/labeler.cc, line 19 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/19#-MfK0Gj92GniyFH2V16V:-MfK0Gj92GniyFH2V16W:bkha3ab) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-core-serving/blob/12ec4d7d5b8ede032bfd76fd0ce09cd942ba9592/src/main/cc/wfa/virtual_people/core/labeler/labeler.cc#L19)):*
> ```
> #include <memory>
> #include <utility>
> #include <vector>
> ```

What are these for?

**Review by efoxepstein — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/19)* status: all files reviewed, 4 unresolved discussions (waiting on @enfreck, @kunyuchen, @lenjoy, @mpatel24, @oliver-amzn, @tcsnfkx, and @wliue)

___
*[src/main/cc/wfa/virtual_people/core/labeler/labeler.cc, line 19 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/19#-MfK0Gj92GniyFH2V16V:-MfK0zMK7zIWcVCIKP7U:b-f5mfxu) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-core-serving/blob/12ec4d7d5b8ede032bfd76fd0ce09cd942ba9592/src/main/cc/wfa/virtual_people/core/labeler/labeler.cc#L19)):*
<details><summary><i>Previously, wliue (Wei Liu) wrote…</i></summary><blockquote>

> ```
> #include <memory>
> #include <utility>
> #include <vector>
> ```

What are these for?
</blockquote></details>

`memory` provides `std::unique_ptr`, `vector` provides `std::vector`, `utility` provides `std::move`

**Review by enfreck — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/19)* status: 27 of 31 files reviewed, 3 unresolved discussions (waiting on @efoxepstein, @kunyuchen, @lenjoy, @mpatel24, @oliver-amzn, @tcsnfkx, and @wliue)

___
*[WORKSPACE, line 29 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/19#-MfJnqTeCc1sXNs8mPMp:-MfKDSB81LqwwdozkpUx:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-core-serving/blob/12ec4d7d5b8ede032bfd76fd0ce09cd942ba9592/WORKSPACE#L29)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Can this be deleted? It should be provided by `common-cpp` (might need to update `@com_google_farmhash` to `@farmhash` if we have a mismatch there.
</blockquote></details>

Done.
___
*[WORKSPACE, line 42 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/19#-MfJvTWZ2I71wSKF_8U8:-MfKDSw66ieKHkZzM_V0:b778gay) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-core-serving/blob/12ec4d7d5b8ede032bfd76fd0ce09cd942ba9592/WORKSPACE#L42)):*
<details><summary><i>Previously, wliue (Wei Liu) wrote…</i></summary><blockquote>

This should be deleted, correct?
</blockquote></details>

virtual-people-common still needs it.
___
*[src/main/cc/wfa/virtual_people/core/model/utils/distributed_consistent_hashing.cc, line 71 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/19#-MfJocGI3-OUN73P6BQ4:-MfKD_qZ88bBY8alvWWy:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-core-serving/blob/12ec4d7d5b8ede032bfd76fd0ce09cd942ba9592/src/main/cc/wfa/virtual_people/core/model/utils/distributed_consistent_hashing.cc#L71)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Can you remove the unnecessary outer parens here please while you're updating this line of code?
</blockquote></details>

Done.

**Review by wliue — APPROVED** [review]
> Reviewed 27 of 31 files at r1, 4 of 4 files at r2.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/19)* status: all files reviewed, 3 unresolved discussions (waiting on @efoxepstein, @kunyuchen, @lenjoy, @mpatel24, @oliver-amzn, @tcsnfkx, and @wliue)

**Review by efoxepstein — APPROVED** [review]
> Reviewed 4 of 4 files at r2.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/19)* status: all files reviewed, 1 unresolved discussion (waiting on @kunyuchen, @lenjoy, @mpatel24, @oliver-amzn, @tcsnfkx, and @wliue)

**Comment by wliue** [comment]
BTW, the majority of the changes in this PR are for clang-format and lint. How about do a standalone PR to fix those first?

**Review by efoxepstein — APPROVED** [review]
Those will disappear from this PR after rebasing https://github.com/world-federation-of-advertisers/virtual-people-core-serving/pull/15 into this (presuming that gets submitted first).

> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/19#-:-MfKj3R_4EjSy8bhNZP5:bv4iut9)* status: all files reviewed, 1 unresolved discussion (waiting on @kunyuchen, @lenjoy, @mpatel24, @oliver-amzn, @tcsnfkx, and @wliue)

**Review by efoxepstein — APPROVED** [review]
> Reviewed 34 of 34 files at r3.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/19)* status: all files reviewed, 1 unresolved discussion (waiting on @kunyuchen, @lenjoy, @mpatel24, @oliver-amzn, @stevenwarejones, @tcsnfkx, and @wliue)

**Review by stevenwarejones — CHANGES_REQUESTED** [review]
> Reviewed 11 of 31 files at r1, 2 of 4 files at r2, 20 of 34 files at r3.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/19)* status: 42 of 48 files reviewed, 8 unresolved discussions (waiting on @efoxepstein, @enfreck, @kunyuchen, @lenjoy, @mpatel24, @oliver-amzn, @tcsnfkx, and @wliue)

___
*[CPPLINT.cfg, line 1 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/19#-MfcN_2a3GfHzvwsSQ3d:-MfcN_2a3GfHzvwsSQ3e:bsbgmg3) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-core-serving/blob/57efe4606422347f9b21115f3a929893d9d60d93/CPPLINT.cfg#L1)):*
> ```INI
> set noparent
> ```

shouldn't this file reside in common, not in virtual-people?
___
*[src/main/cc/wfa/virtual_people/core/labeler/labeler_test.cc, line 1 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/19#-MfcOrLMCiBEo8PERdsW:-MfcOrLMCiBEo8PERdsX:bs80e1a) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-core-serving/blob/57efe4606422347f9b21115f3a929893d9d60d93/src/main/cc/wfa/virtual_people/core/labeler/labeler_test.cc#L1)):*
> ```cpp
> // Copyright 2021 The Cross-Media Measurement Authors
> ```

was this file added by mistake? It already exists in `test`
___
*[src/main/cc/wfa/virtual_people/core/model/branch_node_impl_test.cc, line 1 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/19#-MfcP3Gq5TYFn76oBYEX:-MfcP3Gq5TYFn76oBYEY:b-7ropln) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-core-serving/blob/57efe4606422347f9b21115f3a929893d9d60d93/src/main/cc/wfa/virtual_people/core/model/branch_node_impl_test.cc#L1)):*
> ```cpp
> // Copyright 2021 The Cross-Media Measurement Authors
> ```

ditto
___
*[src/main/cc/wfa/virtual_people/core/model/conditional_assignment_impl_test.cc, line 2 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/19#-MfcP9RWEVLwJyo1yZ04:-MfcP9RWEVLwJyo1yZ05:b-7ropln) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-core-serving/blob/57efe4606422347f9b21115f3a929893d9d60d93/src/main/cc/wfa/virtual_people/core/model/conditional_assignment_impl_test.cc#L2)):*
> ```cpp
> // Copyright 2021 The Cross-Media Measurement Authors
> //
> ```

ditto
___
*[src/main/cc/wfa/virtual_people/core/model/conditional_merge_impl_test.cc, line 1 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/19#-MfcPDwC57YH1LYJUCMl:-MfcPDwC57YH1LYJUCMm:b-7ropln) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-core-serving/blob/57efe4606422347f9b21115f3a929893d9d60d93/src/main/cc/wfa/virtual_people/core/model/conditional_merge_impl_test.cc#L1)):*
> ```cpp
> // Copyright 2021 The Cross-Media Measurement Authors
> ```

ditto
___
*[src/main/cc/wfa/virtual_people/core/model/update_matrix_impl_test.cc, line 2 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/19#-MfcPHodEmY_NdpMZM78:-MfcPHodEmY_NdpMZM79:b-7ropln) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-core-serving/blob/57efe4606422347f9b21115f3a929893d9d60d93/src/main/cc/wfa/virtual_people/core/model/update_matrix_impl_test.cc#L2)):*
> ```cpp
> // Copyright 2021 The Cross-Media Measurement Authors
> //
> ```

ditto
___
*[src/main/cc/wfa/virtual_people/core/model/update_tree_impl_test.cc, line 3 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/19#-MfcPJCPBZVBckQRmEu7:-MfcPJCPBZVBckQRmEu8:b-7ropln) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-core-serving/blob/57efe4606422347f9b21115f3a929893d9d60d93/src/main/cc/wfa/virtual_people/core/model/update_tree_impl_test.cc#L3)):*
> ```cpp
> // Copyright 2021 The Cross-Media Measurement Authors
> //
> // Licensed under the Apache License, Version 2.0 (the "License");
> ```

ditto

**Review by enfreck — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/19)* status: 42 of 48 files reviewed, 8 unresolved discussions (waiting on @efoxepstein, @enfreck, @kunyuchen, @lenjoy, @mpatel24, @oliver-amzn, @stevenwarejones, @tcsnfkx, and @wliue)

___
*[CPPLINT.cfg, line 1 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/19#-MfcN_2a3GfHzvwsSQ3d:-Mfch9bj4eaokXi0yWA8:b-ooq4s0) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-core-serving/blob/57efe4606422347f9b21115f3a929893d9d60d93/CPPLINT.cfg#L1)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

shouldn't this file reside in common, not in virtual-people?
</blockquote></details>

This file is needed to make sure the Linter runs correctly.
___
*[src/main/cc/wfa/virtual_people/core/labeler/labeler_test.cc, line 1 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/19#-MfcOrLMCiBEo8PERdsW:-MfchI868fhMgdTz4BvI:b-vr9v52) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-core-serving/blob/57efe4606422347f9b21115f3a929893d9d60d93/src/main/cc/wfa/virtual_people/core/labeler/labeler_test.cc#L1)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

was this file added by mistake? It already exists in `test`
</blockquote></details>

I think Reviewable might just be showing these files from a previous revision. They are gone on my local branch and I am unable to push again since there are no updates.

**Review by enfreck — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/19)* status: 42 of 48 files reviewed, 8 unresolved discussions (waiting on @efoxepstein, @enfreck, @kunyuchen, @lenjoy, @mpatel24, @oliver-amzn, @stevenwarejones, @tcsnfkx, and @wliue)

___
*[src/main/cc/wfa/virtual_people/core/labeler/labeler_test.cc, line 1 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/19#-MfcOrLMCiBEo8PERdsW:-Mfcj_DZElo41CiXO85U:b88a6w2) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-core-serving/blob/57efe4606422347f9b21115f3a929893d9d60d93/src/main/cc/wfa/virtual_people/core/labeler/labeler_test.cc#L1)):*
<details><summary><i>Previously, enfreck wrote…</i></summary><blockquote>

I think Reviewable might just be showing these files from a previous revision. They are gone on my local branch and I am unable to push again since there are no updates.
</blockquote></details>

Actually, turns out something weird was happening on my end.  They should all be deleted now.

**Review by efoxepstein — APPROVED** [review]
> Reviewed 6 of 6 files at r5.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/19)* status: all files reviewed, 8 unresolved discussions (waiting on @enfreck, @kunyuchen, @lenjoy, @mpatel24, @oliver-amzn, @stevenwarejones, @tcsnfkx, and @wliue)

**Review by stevenwarejones — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/19)* status: all files reviewed, 3 unresolved discussions (waiting on @enfreck, @kunyuchen, @lenjoy, @mpatel24, @oliver-amzn, @stevenwarejones, @tcsnfkx, and @wliue)

___
*[CPPLINT.cfg, line 1 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/19#-MfcN_2a3GfHzvwsSQ3d:-MfcjexrD0MT_-NZ4f_E:b-xglivz) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-core-serving/blob/57efe4606422347f9b21115f3a929893d9d60d93/CPPLINT.cfg#L1)):*
<details><summary><i>Previously, enfreck wrote…</i></summary><blockquote>

This file is needed to make sure the Linter runs correctly.
</blockquote></details>

can't the linter pull this in as a build file? What if we included it `/build/wfa` and added it to `exports_files(["...` .... I guess we could take care of this later since the other repos haven't done this
___
*[src/main/cc/wfa/virtual_people/core/labeler/labeler_test.cc, line 1 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/19#-MfcOrLMCiBEo8PERdsW:-MfcjUb--EE0KBXpGJKH:bgh6g40) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-core-serving/blob/57efe4606422347f9b21115f3a929893d9d60d93/src/main/cc/wfa/virtual_people/core/labeler/labeler_test.cc#L1)):*
<details><summary><i>Previously, enfreck wrote…</i></summary><blockquote>

I think Reviewable might just be showing these files from a previous revision. They are gone on my local branch and I am unable to push again since there are no updates.
</blockquote></details>

looks like you fixed it

**Review by enfreck — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/19)* status: all files reviewed, 3 unresolved discussions (waiting on @kunyuchen, @lenjoy, @mpatel24, @oliver-amzn, @stevenwarejones, @tcsnfkx, and @wliue)

___
*[CPPLINT.cfg, line 1 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/19#-MfcN_2a3GfHzvwsSQ3d:-MfcsFUE0hqaJRRBWlhp:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-core-serving/blob/57efe4606422347f9b21115f3a929893d9d60d93/CPPLINT.cfg#L1)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

can't the linter pull this in as a build file? What if we included it `/build/wfa` and added it to `exports_files(["...` .... I guess we could take care of this later since the other repos haven't done this
</blockquote></details>

Done.

**Review by enfreck — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/19)* status: all files reviewed, 3 unresolved discussions (waiting on @kunyuchen, @lenjoy, @mpatel24, @oliver-amzn, @stevenwarejones, @tcsnfkx, and @wliue)

___
*[src/main/cc/wfa/virtual_people/core/labeler/labeler_test.cc, line 1 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/19#-MfcOrLMCiBEo8PERdsW:-MfcsJfXC0SYOCa85_Pi:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-core-serving/blob/57efe4606422347f9b21115f3a929893d9d60d93/src/main/cc/wfa/virtual_people/core/labeler/labeler_test.cc#L1)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

looks like you fixed it
</blockquote></details>

Done.

**Review by efoxepstein — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/19)* status: all files reviewed, 3 unresolved discussions (waiting on @stevenwarejones and @wliue)

**Review by efoxepstein — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/19)* status: all files reviewed, 3 unresolved discussions (waiting on @stevenwarejones and @wliue)

**Review by efoxepstein — APPROVED** [review]
> Dismissed @stevenwarejones from a discussion.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/19)* status: all files reviewed, 2 unresolved discussions (waiting on @stevenwarejones and @wliue)

___
*[CPPLINT.cfg, line 1 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/19#-MfcN_2a3GfHzvwsSQ3d:-MfcycZVC3iIoYFGHH9J:bsgm2it) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-core-serving/blob/57efe4606422347f9b21115f3a929893d9d60d93/CPPLINT.cfg#L1)):*
<details><summary><i>Previously, enfreck wrote…</i></summary><blockquote>

Done.
</blockquote></details>

The linter doesn't execute Bazel so this would require some pretty big changes, I think.

**Review by efoxepstein — APPROVED** [review]
> Dismissed @wliue from a discussion.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/19)* status: all files reviewed, 1 unresolved discussion (waiting on @stevenwarejones)

**Review by enfreck — COMMENTED** [review]
> Dismissed @stevenwarejones from a discussion.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/19)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @enfreck)

**Pull request merged**
