### PR TITLE
Implement stop_node and UpdateTree.

### PR DESCRIPTION
**Pull request by tcsnfkx**
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/13)

### CODE REVIEW

**Review by efoxepstein — CHANGES_REQUESTED** [review]
> Reviewed 9 of 9 files at r1.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/13)* status: all files reviewed, 4 unresolved discussions (waiting on @EvgSkv, @kunyuchen, @lenjoy, @mpatel24, @my2457, @oliver-amzn, @tcsnfkx, and @wliue)

___
*[src/main/cc/wfa/virtual_people/core/model/BUILD.bazel, line 13 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/13#-Mc_ThDmCJB3WY1iSIY1:-Mc_ThDmCJB3WY1iSIY2:bg9nabz) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-core-serving/blob/e5198ae7c3908177b3551d82aa5e80d27ebc032d/src/main/cc/wfa/virtual_people/core/model/BUILD.bazel#L13)):*
> ```Starlark
>         "model_node.cc",
>         "population_node_impl.cc",
>         "//src/main/cc/wfa/virtual_people/core/model/attributes_updater:attributes_updater.cc",
> ```

Please define a bazel `cc_library` in `attributed_updater` and just depend on that instead.
___
*[src/main/cc/wfa/virtual_people/core/model/stop_node_impl.h, line 32 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/13#-Mc_Txx30ztoih2AX8x2:-Mc_Txx30ztoih2AX8x3:bv7gg79) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-core-serving/blob/e5198ae7c3908177b3551d82aa5e80d27ebc032d/src/main/cc/wfa/virtual_people/core/model/stop_node_impl.h#L32)):*
> ```objc
>   // Users should never call the factory function or constructor of the derived
>   // class directly.
>   static std::unique_ptr<StopNodeImpl> Build(const CompiledNode& node_config) {
> ```

For consistency, would it make sense to return a StatusOr<unique_ptr<StopNodeImpl>> even if you don't use it to futureproof the API and for consistency?
___
*[src/main/cc/wfa/virtual_people/core/model/attributes_updater/BUILD.bazel, line 5 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/13#-Mc_UKkm7UtGFGwnbwvi:-Mc_UKkm7UtGFGwnbwvj:bpsldj7) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-core-serving/blob/e5198ae7c3908177b3551d82aa5e80d27ebc032d/src/main/cc/wfa/virtual_people/core/model/attributes_updater/BUILD.bazel#L5)):*
> ```Starlark
> package(default_visibility = ["//src:__subpackages__"])
> 
> exports_files([
> ```

Why not a `cc_library` with these?
___
*[src/main/cc/wfa/virtual_people/core/model/attributes_updater/update_tree_impl_test.cc, line 1 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/13#-Mc_Uf775nIq2ESb5oXD:-Mc_Uf775nIq2ESb5oXE:b-1ke707) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-core-serving/blob/e5198ae7c3908177b3551d82aa5e80d27ebc032d/src/main/cc/wfa/virtual_people/core/model/attributes_updater/update_tree_impl_test.cc#L1)):*
> ```cpp
> // Copyright 2021 The Cross-Media Measurement Authors
> ```

I'm not sure how I missed this, but in other C++ projects we've been putting tests in `src/test/cc/...` instead of `src/main/cc/...`. We should make this repo consistent.

**Review by tcsnfkx — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/13)* status: 5 of 9 files reviewed, 4 unresolved discussions (waiting on @efoxepstein, @EvgSkv, @kunyuchen, @lenjoy, @mpatel24, @my2457, @oliver-amzn, and @wliue)

___
*[src/main/cc/wfa/virtual_people/core/model/BUILD.bazel, line 13 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/13#-Mc_ThDmCJB3WY1iSIY1:-Mcjvuf_2SP4PogVIUba:bvwozi3) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-core-serving/blob/e5198ae7c3908177b3551d82aa5e80d27ebc032d/src/main/cc/wfa/virtual_people/core/model/BUILD.bazel#L13)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Please define a bazel `cc_library` in `attributed_updater` and just depend on that instead.
</blockquote></details>

With ```update_tree```, ```attributed_updater``` and ```model_node``` have to depend on each other.
___
*[src/main/cc/wfa/virtual_people/core/model/stop_node_impl.h, line 32 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/13#-Mc_Txx30ztoih2AX8x2:-MckBHC--EDulkuKXVTl:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-core-serving/blob/e5198ae7c3908177b3551d82aa5e80d27ebc032d/src/main/cc/wfa/virtual_people/core/model/stop_node_impl.h#L32)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

For consistency, would it make sense to return a StatusOr<unique_ptr<StopNodeImpl>> even if you don't use it to futureproof the API and for consistency?
</blockquote></details>

Done.
___
*[src/main/cc/wfa/virtual_people/core/model/attributes_updater/BUILD.bazel, line 5 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/13#-Mc_UKkm7UtGFGwnbwvi:-Mcjwht08gzDVc3I_Eb4:bvwozi3) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-core-serving/blob/e5198ae7c3908177b3551d82aa5e80d27ebc032d/src/main/cc/wfa/virtual_people/core/model/attributes_updater/BUILD.bazel#L5)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Why not a `cc_library` with these?
</blockquote></details>

With ```update_tree```, ```attributed_updater``` and ```model_node``` have to depend on each other.
___
*[src/main/cc/wfa/virtual_people/core/model/attributes_updater/update_tree_impl_test.cc, line 1 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/13#-Mc_Uf775nIq2ESb5oXD:-McjwsxK8mbGQgwEVHWl:b-tz3gkt) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-core-serving/blob/e5198ae7c3908177b3551d82aa5e80d27ebc032d/src/main/cc/wfa/virtual_people/core/model/attributes_updater/update_tree_impl_test.cc#L1)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

I'm not sure how I missed this, but in other C++ projects we've been putting tests in `src/test/cc/...` instead of `src/main/cc/...`. We should make this repo consistent.
</blockquote></details>

Acknowledge. We will have future PRs to move the tests to ```src/test/cc/...```.

**Review by efoxepstein — CHANGES_REQUESTED** [review]
> Reviewed 4 of 4 files at r2.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/13)* status: all files reviewed, 1 unresolved discussion (waiting on @EvgSkv, @kunyuchen, @lenjoy, @mpatel24, @my2457, @oliver-amzn, @tcsnfkx, and @wliue)

___
*[src/main/cc/wfa/virtual_people/core/model/BUILD.bazel, line 13 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/13#-Mc_ThDmCJB3WY1iSIY1:-MclBmPM1wxwYG53p5O6:b-vl51eg) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-core-serving/blob/e5198ae7c3908177b3551d82aa5e80d27ebc032d/src/main/cc/wfa/virtual_people/core/model/BUILD.bazel#L13)):*
<details><summary><i>Previously, tcsnfkx wrote…</i></summary><blockquote>

With ```update_tree```, ```attributed_updater``` and ```model_node``` have to depend on each other.
</blockquote></details>

Can you forward-declare `ModelNode` in `attribute_updater.{h,cc}` instead? It doesn't look like it requires a full definition.
___
*[src/main/cc/wfa/virtual_people/core/model/attributes_updater/BUILD.bazel, line 5 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/13#-Mc_UKkm7UtGFGwnbwvi:-MclEE-w02FqxLfVdZ99:brzj5k5) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-core-serving/blob/e5198ae7c3908177b3551d82aa5e80d27ebc032d/src/main/cc/wfa/virtual_people/core/model/attributes_updater/BUILD.bazel#L5)):*
<details><summary><i>Previously, tcsnfkx wrote…</i></summary><blockquote>

With ```update_tree```, ```attributed_updater``` and ```model_node``` have to depend on each other.
</blockquote></details>

Moving discussion to other comment; closing this one.

**Review by tcsnfkx — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/13)* status: all files reviewed, 1 unresolved discussion (waiting on @efoxepstein, @EvgSkv, @kunyuchen, @lenjoy, @mpatel24, @my2457, @oliver-amzn, and @wliue)

___
*[src/main/cc/wfa/virtual_people/core/model/BUILD.bazel, line 13 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/13#-Mc_ThDmCJB3WY1iSIY1:-Mcm5JGc-DJ4UevWVkaV:bvl22kv) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-core-serving/blob/e5198ae7c3908177b3551d82aa5e80d27ebc032d/src/main/cc/wfa/virtual_people/core/model/BUILD.bazel#L13)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Can you forward-declare `ModelNode` in `attribute_updater.{h,cc}` instead? It doesn't look like it requires a full definition.
</blockquote></details>

The definition of ```UpdateTree``` requires the methods of ```ModelNode``` to build. So we still need the ```model_node``` target in ```attributes_updater```. Having a separate build target for ```model_node.h``` without the definitions could help, but I think it is even harder to read.

**Review by efoxepstein — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/13)* status: all files reviewed, 1 unresolved discussion (waiting on @EvgSkv, @kunyuchen, @lenjoy, @mpatel24, @my2457, @oliver-amzn, @tcsnfkx, and @wliue)

___
*[src/main/cc/wfa/virtual_people/core/model/BUILD.bazel, line 13 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/13#-Mc_ThDmCJB3WY1iSIY1:-Mco65jO5U0ne0GSHMXs:bynpiux) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-core-serving/blob/e5198ae7c3908177b3551d82aa5e80d27ebc032d/src/main/cc/wfa/virtual_people/core/model/BUILD.bazel#L13)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

What about just moving everything in the `attributes_updater` folder up into this one? (The parent directory.) Then it would be very natural to combine them into one library.

See also https://yaqs.corp.google.com/eng/q/6472996124622848#a4508997144150016 as a citation for a cc_library for only the headers.
</blockquote></details>

Also, what about pulling `ModelNode::Build` out into a separate library (as `BuildModelNode`). Would that solve some of the circularity?

In general if there's a circular dependency, there's frequently some design issue causing it.

**Review by tcsnfkx — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/13)* status: 2 of 23 files reviewed, 1 unresolved discussion (waiting on @efoxepstein, @EvgSkv, @kunyuchen, @lenjoy, @mpatel24, @my2457, @oliver-amzn, and @wliue)

___
*[src/main/cc/wfa/virtual_people/core/model/BUILD.bazel, line 13 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/13#-Mc_ThDmCJB3WY1iSIY1:-Mconsb2-r76yOQ8EIKZ:b-6pyajs) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-core-serving/blob/e5198ae7c3908177b3551d82aa5e80d27ebc032d/src/main/cc/wfa/virtual_people/core/model/BUILD.bazel#L13)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Also, what about pulling `ModelNode::Build` out into a separate library (as `BuildModelNode`). Would that solve some of the circularity?

In general if there's a circular dependency, there's frequently some design issue causing it.
</blockquote></details>

Everything in ```attributes_updater``` dir was moved to ```model_node``` dir.

```ModelNode::Build``` is not the only method used here. We need ```Apply()``` also.

Based on the discussion in the link, the first option is to put the circular dependencies in the same build target. The option of forward declaration and separating .h and .cc build target are also mentioned, but it will cause further inconvenience when other components depend on ```model_node```.

**Review by efoxepstein — APPROVED** [review]
> Reviewed 21 of 21 files at r3.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/13)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @EvgSkv, @kunyuchen, @lenjoy, @mpatel24, @my2457, @oliver-amzn, and @wliue)

**Review by mpatel24 — APPROVED** [review]

**Pull request merged**
