### PR TITLE
Do not set virtual person id when the node is an empty population pool.

### PR DESCRIPTION
**Pull request by tcsnfkx**
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/24)

### CODE REVIEW

**Review by efoxepstein — APPROVED** [review]
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/24)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @EvgSkv, @kunyuchen, @lenjoy, @mpatel24, @my2457, @oliver-amzn, and @wliue)

**Review by wliue — CHANGES_REQUESTED** [review]
> Reviewed 2 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/24)* status: all files reviewed, 5 unresolved discussions (waiting on @EvgSkv, @kunyuchen, @lenjoy, @mpatel24, @my2457, @oliver-amzn, and @tcsnfkx)

___
*[-- commits, line 3 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/24#-MhQmxKO08plK7WdcRrH:-MhQmxKO08plK7WdcRrI:b-1noxt7) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-core-serving/blob/437de5be5250c240cd56fa0d7db568eca459f09a/-- commits#L3)):*
Update the PR description. This is for virtual_person_id, not demo.
___
*[src/main/cc/wfa/virtual_people/core/model/population_node_impl.h, line 40 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/24#-MhQkZED-xp98n0bUVuw:-MhQkZED-xp98n0bUVux:b-uod5t1) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-core-serving/blob/437de5be5250c240cd56fa0d7db568eca459f09a/src/main/cc/wfa/virtual_people/core/model/population_node_impl.h#L40)):*
> ```objc
>   // Returns error status if any of the following happens:
>   // * @node_config.population_node is not set.
>   // * The total population of the pools is 0 and the pools does not reporesent
> ```

Typo: -> represent
does not -> do not
___
*[src/main/cc/wfa/virtual_people/core/model/population_node_impl.h, line 61 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/24#-MhQksAi4FrLKfIE-Fx9:-MhQksAi4FrLKfIE-FxA:b-1hqs8d) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-core-serving/blob/437de5be5250c240cd56fa0d7db568eca459f09a/src/main/cc/wfa/virtual_people/core/model/population_node_impl.h#L61)):*
> ```objc
> 
>  private:
>   // Used to get a virtual person id. Be nullptr when the pools represents an
> ```

Be nullptr -> Is nullptr
represents -> represent
___
*[src/main/cc/wfa/virtual_people/core/model/population_node_impl.cc, line 36 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/24#-MhQlajh9tPUj2uYa_P_:-MhQlajh9tPUj2uYa_Pa:b8c5hb7) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-core-serving/blob/437de5be5250c240cd56fa0d7db568eca459f09a/src/main/cc/wfa/virtual_people/core/model/population_node_impl.cc#L36)):*
> ```cpp
> namespace wfa_virtual_people {
> 
> // Check if the @pools represents an empty population pool.
> ```

Nit: maybe -> represent.
___
*[src/test/cc/wfa/virtual_people/core/model/population_node_impl_test.cc, line 187 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/24#-MhQmciP5ek09ee0nio0:-MhQmciP5ek09ee0nio1:b-7kld0q) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-core-serving/blob/437de5be5250c240cd56fa0d7db568eca459f09a/src/test/cc/wfa/virtual_people/core/model/population_node_impl_test.cc#L187)):*
> ```
>   // The node is invalid as the total pools size is 0.
> ```
Update this comment.

**Review by tcsnfkx — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/24)* status: 0 of 3 files reviewed, 4 unresolved discussions (waiting on @efoxepstein, @EvgSkv, @kunyuchen, @lenjoy, @mpatel24, @my2457, @oliver-amzn, and @wliue)

___
*[-- commits, line 3 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/24#-MhQmxKO08plK7WdcRrH:-MhRiSEi53DmxbT86Oqy:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-core-serving/blob/437de5be5250c240cd56fa0d7db568eca459f09a/-- commits#L3)):*
<details><summary><i>Previously, wliue (Wei Liu) wrote…</i></summary><blockquote>

Update the PR description. This is for virtual_person_id, not demo.
</blockquote></details>

Done.
___
*[src/main/cc/wfa/virtual_people/core/model/population_node_impl.h, line 40 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/24#-MhQkZED-xp98n0bUVuw:-MhRkIlk67g3DhYm7BuE:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-core-serving/blob/437de5be5250c240cd56fa0d7db568eca459f09a/src/main/cc/wfa/virtual_people/core/model/population_node_impl.h#L40)):*
<details><summary><i>Previously, wliue (Wei Liu) wrote…</i></summary><blockquote>

Typo: -> represent
does not -> do not
</blockquote></details>

Done.
___
*[src/main/cc/wfa/virtual_people/core/model/population_node_impl.h, line 61 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/24#-MhQksAi4FrLKfIE-Fx9:-MhRkJE5DFNxM9OTIOL0:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-core-serving/blob/437de5be5250c240cd56fa0d7db568eca459f09a/src/main/cc/wfa/virtual_people/core/model/population_node_impl.h#L61)):*
<details><summary><i>Previously, wliue (Wei Liu) wrote…</i></summary><blockquote>

Be nullptr -> Is nullptr
represents -> represent
</blockquote></details>

Done.
___
*[src/test/cc/wfa/virtual_people/core/model/population_node_impl_test.cc, line 187 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/24#-MhQmciP5ek09ee0nio0:-MhRkL-HCX5sXPR5gvLJ:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-core-serving/blob/437de5be5250c240cd56fa0d7db568eca459f09a/src/test/cc/wfa/virtual_people/core/model/population_node_impl_test.cc#L187)):*
<details><summary><i>Previously, wliue (Wei Liu) wrote…</i></summary><blockquote>

> ```
>   // The node is invalid as the total pools size is 0.
> ```
Update this comment.
</blockquote></details>

Done.

**Review by efoxepstein — APPROVED** [review]
> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/24)* status: all files reviewed, 4 unresolved discussions (waiting on @EvgSkv, @kunyuchen, @lenjoy, @mpatel24, @my2457, @oliver-amzn, and @wliue)

**Review by wliue — APPROVED** [review]
> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/24)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @EvgSkv, @kunyuchen, @lenjoy, @mpatel24, @my2457, and @oliver-amzn)

**Review by mpatel24 — APPROVED** [review]

**Review by wliue — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/24)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @EvgSkv, @kunyuchen, @lenjoy, @my2457, and @oliver-amzn)

**Pull request merged**
