### PR TITLE
Update the Ubuntu version for build and tests, and the Bazel version.

### PR DESCRIPTION
**Pull request by tcsnfkx**

### CODE REVIEW

**Comment by wfa-reviewable** [comment]
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/75)

**Review by wliue — APPROVED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/75)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @EvgSkv, @Marco-Premier, @SanjayVas, @stevenwarejones, and @wangyaopw)

**Review by Marco-Premier — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/75)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @EvgSkv, @SanjayVas, @stevenwarejones, and @wangyaopw)

**Review by SanjayVas — COMMENTED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/75)* status: all files reviewed, 1 unresolved discussion

___
*[`.github/workflows/build-test.yml` line 31 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/75#-N_AzM6i2lJWw_4FBZfi:-N_AzM6j2_BYzQu5cbhc:bvwgqz7) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-core-serving/blob/56329b56398a57ff954d7e398f2c5168ff189865/.github/workflows/build-test.yml#L31)):*
> ```YAML
>     steps:
>       - name: Check out revision
>         uses: actions/checkout@v2
> ```

This may work for now, but note that checkout@v2 is also deprecated. This is also using the older v1 of our actions. I'd recommend just copying a newer workflow, e.g. https://github.com/world-federation-of-advertisers/consent-signaling-client/blob/main/.github/workflows/build-test.yml

**Pull request merged**
