### PR TITLE
Create Labeler API

### PR DESCRIPTION
**Pull request by tcsnfkx**
Remove the method to resolve child reference in ModelNode, which will be handled in ModelNode::Build.
Implement Labeler API.

---
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/11)

### CODE REVIEW

**Review by efoxepstein — CHANGES_REQUESTED** [review]
> Reviewed 11 of 11 files at r1.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/11)* status: all files reviewed, 4 unresolved discussions (waiting on @EvgSkv, @kunyuchen, @lenjoy, @mpatel24, @my2457, @oliver-amzn, @tcsnfkx, and @wliue)

___
*[src/main/cc/wfa/virtual_people/core/labeler/labeler.cc, line 56 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/11#-McFgXse8tn3WAZ4-Abg:-McFgXse8tn3WAZ4-Abh:bn4wj4u) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-core-serving/blob/bc07f5194465e43bc0b166461cc981ed49c2d258/src/main/cc/wfa/virtual_people/core/labeler/labeler.cc#L56)):*
> ```cpp
>       }
>       ASSIGN_OR_RETURN(
>           node_refs[node_config.index()],
> ```

This is doing a double lookup. Instead, just use `try_emplace` or `insert`, which return a boolean if they actually inserted.
___
*[src/main/cc/wfa/virtual_people/core/labeler/labeler.cc, line 86 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/11#-McFhJ6o24MzzFts5W1I:-McFhJ6o24MzzFts5W1J:bimck28) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-core-serving/blob/bc07f5194465e43bc0b166461cc981ed49c2d258/src/main/cc/wfa/virtual_people/core/labeler/labeler.cc#L86)):*
> ```cpp
> }
> 
> void GenerateFingerprintForUserInfo(UserInfo& user_info) {
> ```

Maybe `SetUserInfoFingerprint`? It's not just generating it -- it's also changing the input.
___
*[src/main/cc/wfa/virtual_people/core/labeler/labeler_test.cc, line 99 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/11#-McFhy8k64XZYKc4jBxA:-McFhy8k64XZYKc4jBxB:b-1te7wb) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-core-serving/blob/bc07f5194465e43bc0b166461cc981ed49c2d258/src/main/cc/wfa/virtual_people/core/labeler/labeler_test.cc#L99)):*
> ```cpp
>   // * 60% probability to assign virtual person id 20
>   std::vector<CompiledNode> nodes;
>   nodes.emplace_back();
> ```

FWIW, `emplace_back` returns a mutable reference to the item, so I think you can do `ASSERT_TRUE(ParseFromString("...", &nodes.emplace_back()));`
___
*[src/main/cc/wfa/virtual_people/core/model/branch_node_impl.cc, line 194 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/11#-McFi_HZ2StXKG0oULBY:-McFi_HZ2StXKG0oULBZ:bvezkag) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-core-serving/blob/bc07f5194465e43bc0b166461cc981ed49c2d258/src/main/cc/wfa/virtual_people/core/model/branch_node_impl.cc#L194)):*
> ```cpp
>   }
> 
>   return child_nodes_[selected_index]->Apply(event);
> ```

Defensive check for `0 <= selected_index < child_nodes_.size()`?

**Review by tcsnfkx — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/11)* status: 8 of 11 files reviewed, 4 unresolved discussions (waiting on @efoxepstein, @EvgSkv, @kunyuchen, @lenjoy, @mpatel24, @my2457, @oliver-amzn, and @wliue)

___
*[src/main/cc/wfa/virtual_people/core/labeler/labeler.cc, line 56 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/11#-McFgXse8tn3WAZ4-Abg:-McFzsqu4PQzwXXtG7eh:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-core-serving/blob/bc07f5194465e43bc0b166461cc981ed49c2d258/src/main/cc/wfa/virtual_people/core/labeler/labeler.cc#L56)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

This is doing a double lookup. Instead, just use `try_emplace` or `insert`, which return a boolean if they actually inserted.
</blockquote></details>

Done.
___
*[src/main/cc/wfa/virtual_people/core/labeler/labeler.cc, line 86 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/11#-McFhJ6o24MzzFts5W1I:-McFztrD7iRwpDgybKRV:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-core-serving/blob/bc07f5194465e43bc0b166461cc981ed49c2d258/src/main/cc/wfa/virtual_people/core/labeler/labeler.cc#L86)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Maybe `SetUserInfoFingerprint`? It's not just generating it -- it's also changing the input.
</blockquote></details>

Done.
___
*[src/main/cc/wfa/virtual_people/core/labeler/labeler_test.cc, line 99 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/11#-McFhy8k64XZYKc4jBxA:-McFzvMn4t93A33y83un:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-core-serving/blob/bc07f5194465e43bc0b166461cc981ed49c2d258/src/main/cc/wfa/virtual_people/core/labeler/labeler_test.cc#L99)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

FWIW, `emplace_back` returns a mutable reference to the item, so I think you can do `ASSERT_TRUE(ParseFromString("...", &nodes.emplace_back()));`
</blockquote></details>

Done.
___
*[src/main/cc/wfa/virtual_people/core/model/branch_node_impl.cc, line 194 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/11#-McFi_HZ2StXKG0oULBY:-McFzxYh67y31hQVWc_G:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-core-serving/blob/bc07f5194465e43bc0b166461cc981ed49c2d258/src/main/cc/wfa/virtual_people/core/model/branch_node_impl.cc#L194)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Defensive check for `0 <= selected_index < child_nodes_.size()`?
</blockquote></details>

Done.

**Review by efoxepstein — APPROVED** [review]
> Reviewed 3 of 3 files at r2, 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/11)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @EvgSkv, @kunyuchen, @lenjoy, @mpatel24, @my2457, @oliver-amzn, and @wliue)

**Review by wliue — CHANGES_REQUESTED** [review]
> Reviewed 2 of 11 files at r1.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/11)* status: all files reviewed, 3 unresolved discussions (waiting on @EvgSkv, @kunyuchen, @lenjoy, @mpatel24, @my2457, @oliver-amzn, and @tcsnfkx)

___
*[src/main/cc/wfa/virtual_people/core/labeler/labeler.cc, line 106 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/11#-McKFUYc6uVPljjD2Eeu:-McKFUYc6uVPljjD2Eev:bob47zu) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-core-serving/blob/18696572eb134762e193ff7d45ed0484abea46f6/src/main/cc/wfa/virtual_people/core/labeler/labeler.cc#L106)):*
> ```cpp
>   if (!labeler_input->has_profile_info()) {
>     return;
>   }
> ```

Nit: add a blank line after.
___
*[src/main/cc/wfa/virtual_people/core/labeler/labeler_test.cc, line 413 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/11#-McKGkoZ0pg6yMd3MYsn:-McKGkoZ0pg6yMd3MYso:blo7ak9) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-core-serving/blob/18696572eb134762e193ff7d45ed0484abea46f6/src/main/cc/wfa/virtual_people/core/labeler/labeler_test.cc#L413)):*
> ```cpp
> }
> 
> }  // namespace
> ```

Could add the following cases:
Nodes list has only 1 entry.
Two nodes has the same child node index. For example: root with child [1,2], 1 with child [3], 2 with child [3].
___
*[src/main/cc/wfa/virtual_people/core/model/model_node.h, line 40 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/11#-McKKWI10rkFqqqvyLIt:-McKKWI10rkFqqqvyLIu:b28jv3z) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-core-serving/blob/18696572eb134762e193ff7d45ed0484abea46f6/src/main/cc/wfa/virtual_people/core/model/model_node.h#L40)):*
> ```objc
>   //
>   // @node_refs is the mapping from indexes to the ModelNode objects, which
>   // should contain the child nodes referenced by indexes.
> ```

Could mention that it is an error if a child is referenced by index and is not found in node_refs.

**Review by tcsnfkx — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/11)* status: 9 of 11 files reviewed, 2 unresolved discussions (waiting on @efoxepstein, @EvgSkv, @kunyuchen, @lenjoy, @mpatel24, @my2457, @oliver-amzn, and @wliue)

___
*[src/main/cc/wfa/virtual_people/core/labeler/labeler.cc, line 106 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/11#-McKFUYc6uVPljjD2Eeu:-McL4HZu9C3P_HJIgs83:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-core-serving/blob/18696572eb134762e193ff7d45ed0484abea46f6/src/main/cc/wfa/virtual_people/core/labeler/labeler.cc#L106)):*
<details><summary><i>Previously, wliue (Wei Liu) wrote…</i></summary><blockquote>

Nit: add a blank line after.
</blockquote></details>

Done.
___
*[src/main/cc/wfa/virtual_people/core/labeler/labeler_test.cc, line 413 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/11#-McKGkoZ0pg6yMd3MYsn:-McL4J9e0GKw1qy8IMiu:bdmmvb0) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-core-serving/blob/18696572eb134762e193ff7d45ed0484abea46f6/src/main/cc/wfa/virtual_people/core/labeler/labeler_test.cc#L413)):*
<details><summary><i>Previously, wliue (Wei Liu) wrote…</i></summary><blockquote>

Could add the following cases:
Nodes list has only 1 entry.
Two nodes has the same child node index. For example: root with child [1,2], 1 with child [3], 2 with child [3].
</blockquote></details>

Added a test case for a child node referenced by multiple parent nodes. I think we should avoid mixing different errors in the same test case.
___
*[src/main/cc/wfa/virtual_people/core/model/model_node.h, line 40 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/11#-McKKWI10rkFqqqvyLIt:-McL43QiAPrdOORiSbNL:b-xmqdi8) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-core-serving/blob/18696572eb134762e193ff7d45ed0484abea46f6/src/main/cc/wfa/virtual_people/core/model/model_node.h#L40)):*
<details><summary><i>Previously, wliue (Wei Liu) wrote…</i></summary><blockquote>

Could mention that it is an error if a child is referenced by index and is not found in node_refs.
</blockquote></details>

This is mentioned in branch_node.h.

**Review by wliue — CHANGES_REQUESTED** [review]
> Reviewed 2 of 11 files at r1, 2 of 2 files at r4.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/11)* status: all files reviewed, 2 unresolved discussions (waiting on @EvgSkv, @kunyuchen, @lenjoy, @mpatel24, @my2457, @oliver-amzn, and @tcsnfkx)

___
*[src/main/cc/wfa/virtual_people/core/labeler/labeler_test.cc, line 413 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/11#-McKGkoZ0pg6yMd3MYsn:-McLDD3E5VYVvD--rWXP:b-pw9gi2) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-core-serving/blob/18696572eb134762e193ff7d45ed0484abea46f6/src/main/cc/wfa/virtual_people/core/labeler/labeler_test.cc#L413)):*
<details><summary><i>Previously, tcsnfkx wrote…</i></summary><blockquote>

Added a test case for a child node referenced by multiple parent nodes. I think we should avoid mixing different errors in the same test case.
</blockquote></details>

What are the different errors in the example above?
Also, please add a case for nodes list length = 1, to verify that it works if the entire tree is defined explicitly as one node.
___
*[src/main/cc/wfa/virtual_people/core/model/model_node.h, line 40 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/11#-McKKWI10rkFqqqvyLIt:-McLEFu99BLzT0eQsBlQ:b75xap0) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-core-serving/blob/18696572eb134762e193ff7d45ed0484abea46f6/src/main/cc/wfa/virtual_people/core/model/model_node.h#L40)):*
<details><summary><i>Previously, tcsnfkx wrote…</i></summary><blockquote>

This is mentioned in branch_node.h.
</blockquote></details>

Yes it is mentioned in branch_node.h. However, the comment above says that "Users should never call the factory function or constructor of the derived class directly.", so it could be useful to also mention it here.

**Review by tcsnfkx — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/11)* status: 9 of 11 files reviewed, 2 unresolved discussions (waiting on @efoxepstein, @EvgSkv, @kunyuchen, @lenjoy, @mpatel24, @my2457, @oliver-amzn, and @wliue)

___
*[src/main/cc/wfa/virtual_people/core/labeler/labeler_test.cc, line 413 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/11#-McKGkoZ0pg6yMd3MYsn:-McNVYtpD2hBOmnS9LtS:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-core-serving/blob/18696572eb134762e193ff7d45ed0484abea46f6/src/main/cc/wfa/virtual_people/core/labeler/labeler_test.cc#L413)):*
<details><summary><i>Previously, wliue (Wei Liu) wrote…</i></summary><blockquote>

What are the different errors in the example above?
Also, please add a case for nodes list length = 1, to verify that it works if the entire tree is defined explicitly as one node.
</blockquote></details>

Done.
___
*[src/main/cc/wfa/virtual_people/core/model/model_node.h, line 40 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/11#-McKKWI10rkFqqqvyLIt:-McNVpoF9B0Wj8OiU0Y0:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-core-serving/blob/18696572eb134762e193ff7d45ed0484abea46f6/src/main/cc/wfa/virtual_people/core/model/model_node.h#L40)):*
<details><summary><i>Previously, wliue (Wei Liu) wrote…</i></summary><blockquote>

Yes it is mentioned in branch_node.h. However, the comment above says that "Users should never call the factory function or constructor of the derived class directly.", so it could be useful to also mention it here.
</blockquote></details>

Done.

**Review by efoxepstein — APPROVED** [review]
> Reviewed 1 of 2 files at r4, 2 of 2 files at r5.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/11)* status: all files reviewed, 2 unresolved discussions (waiting on @EvgSkv, @kunyuchen, @lenjoy, @mpatel24, @my2457, @oliver-amzn, and @wliue)

**Review by wliue — APPROVED** [review]
> Reviewed 4 of 11 files at r1, 1 of 1 files at r3, 2 of 2 files at r5.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/11)* status: all files reviewed, 2 unresolved discussions (waiting on @EvgSkv, @kunyuchen, @lenjoy, @mpatel24, @my2457, @oliver-amzn, and @wliue)

**Review by mpatel24 — APPROVED** [review]

**Pull request merged**
