### PR TITLE
Implement the kotlin FieldFiltersMatcher class.

### PR DESCRIPTION
**Pull request by wangyaopw**
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/55)

### CODE REVIEW

**Review by wliue — APPROVED** [review]
> Reviewed 4 of 5 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/55)* status: all files reviewed, 1 unresolved discussion (waiting on @tcsnfkx and @wangyaopw)

___
*[`src/test/kotlin/org/wfanet/virtualpeople/core/model/utils/FieldFiltersMatcherTest.kt` line 13 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/55#-NBTy0m0428JRj1f_Sgc:-NBTy0m0428JRj1f_Sgd:b-3gxefh) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-core-serving/blob/aceeae332321c9583d8dbf6e9fba31919486992b/src/test/kotlin/org/wfanet/virtualpeople/core/model/utils/FieldFiltersMatcherTest.kt#L13)):*
> ```Kotlin
> // WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
> // See the License for the specific language governing permissions and
> // limitations under the \License.
> ```

Seems an extra '\'.



_Code quote:_
```Kotlin
\
```

**Review by wangyaopw — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/55)* status: 4 of 5 files reviewed, 1 unresolved discussion (waiting on @tcsnfkx and @wliue)

___
*[`src/test/kotlin/org/wfanet/virtualpeople/core/model/utils/FieldFiltersMatcherTest.kt` line 13 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/55#-NBTy0m0428JRj1f_Sgc:-NBUJfO08iGdbCLlyMi-:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-core-serving/blob/aceeae332321c9583d8dbf6e9fba31919486992b/src/test/kotlin/org/wfanet/virtualpeople/core/model/utils/FieldFiltersMatcherTest.kt#L13)):*
<details><summary><i>Previously, wliue (Wei Liu) wrote…</i></summary><blockquote>

Seems an extra '\'.
</blockquote></details>

Done.

**Review by wangyaopw — COMMENTED** [review]
> Reviewed 3 of 5 files at r1, 1 of 1 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/55)* status: all files reviewed, 1 unresolved discussion (waiting on @tcsnfkx and @wliue)

**Review by wangyaopw — COMMENTED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/55)* status: all files reviewed, 1 unresolved discussion (waiting on @tcsnfkx and @wliue)

**Review by wangyaopw — COMMENTED** [review]
> Dismissed @wliue from a discussion.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/55)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @tcsnfkx)

**Pull request merged**
