### PR TITLE
Migrate to Bzlmod

### PR DESCRIPTION
**Pull request by stevenwarejones**

### CODE REVIEW

**Review by SanjayVas — CHANGES_REQUESTED** [review]
> Reviewed 16 of 18 files at r1, 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/78)* status: all files reviewed, 2 unresolved discussions (waiting on @Marco-Premier and @stevenwarejones)

___
*[`MODULE.bazel` line 79 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/78#-OCd_4HG8vIlBfseOLVB:-OCd_4HG8vIlBfseOLVC:bvggg8x) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-core-serving/blob/543c4c7c5a6f618f29113b2c0bd184f271b80b87/MODULE.bazel#L79)):*
> ```Starlark
>     name = MAVEN_REPO_NAME,
>     artifacts = [
>         "junit:junit:4.13.2",
> ```

These artifacts should already be included by common-jvm.
___
*[`src/main/kotlin/org/wfanet/virtualpeople/core/model/utils/BUILD.bazel` line 9 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/78#-OCdZaJyBTnfTX6Wu4qo:-OCdZaJyBTnfTX6Wu4qp:bin6hka) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-core-serving/blob/02291d2bc8d48cfbe2e89a0b93e66f9a84998d84/src/main/kotlin/org/wfanet/virtualpeople/core/model/utils/BUILD.bazel#L9)):*
> ```Starlark
>     srcs = glob(["*.kt"]),
>     deps = [
>         #"@maven//:com_google_guava_guava",
> ```

nit: remove commented out line

**Review by stevenwarejones — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/78)* status: all files reviewed, 1 unresolved discussion (waiting on @Marco-Premier and @SanjayVas)

___
*[`MODULE.bazel` line 79 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/78#-OCd_4HG8vIlBfseOLVB:-OCdak8I47SCHBDHFuQc:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-core-serving/blob/543c4c7c5a6f618f29113b2c0bd184f271b80b87/MODULE.bazel#L79)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

These artifacts should already be included by common-jvm.
</blockquote></details>

Done.

**Review by SanjayVas — APPROVED** [review]
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/78)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Marco-Premier)

**Review by stevenwarejones — COMMENTED** [review]
> Reviewed 14 of 18 files at r1, 2 of 4 files at r2, 1 of 2 files at r3, 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/78)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Marco-Premier)

**Pull request merged**
