### PR TITLE
Create integration tests for labeler, and update toy model.

### PR DESCRIPTION
**Pull request by tcsnfkx**
In toy model,
* Add AttributesUpdater to set country_code.
* Use ConditionalAssignment instead of ConditionalMerge to extract demo
from profiles.
* Make the profile type consistent when multiple profile types are set.
* Format the textproto.
Create events to test the "cookied" branch of the toy model.

---
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/30)

### CODE REVIEW

**Review by efoxepstein — APPROVED** [review]
> Reviewed 29 of 29 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/30)* status: all files reviewed, 2 unresolved discussions (waiting on @EvgSkv, @kunyuchen, @lenjoy, @mpatel24, @my2457, @tcsnfkx, and @wliue)

___
*[src/test/cc/wfa/virtual_people/core/labeler/BUILD.bazel, line 23 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/30#-Mts-Tll9kGsAm2Ro-GU:-Mts-Tll9kGsAm2Ro-GV:blirhvg) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-core-serving/blob/a7ec07e1076534d3eee51247931f116c1c76522a/src/test/cc/wfa/virtual_people/core/labeler/BUILD.bazel#L23)):*
> ```Starlark
>     name = "labeler_integration_test",
>     srcs = ["labeler_integration_test.cc"],
>     data = [
> ```

Would something like this work? `data = glob(["//src/test/cc/wfa/virtual_people/core/labeler/test_data/labeler_input_*.textproto", "//src/test/cc/wfa/virtual_people/core/labeler/test_data/labeler_output_*.textproto"])`
___
*[src/test/cc/wfa/virtual_people/core/labeler/labeler_integration_test.cc, line 42 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/30#-Mts0W2WDRwiozYsL3mw:-Mts0W2WDRwiozYsL3mx:be1pm34) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-core-serving/blob/a7ec07e1076534d3eee51247931f116c1c76522a/src/test/cc/wfa/virtual_people/core/labeler/labeler_integration_test.cc#L42)):*
> ```cpp
>                       absl::string_view input_path,
>                       absl::string_view output_path) {
>   CompiledNode root;
> ```

Consider adding something like `SCOPED_TRACE(absl:StrCat("ApplyAndValidate(", model_path, ", ", input_path, ", ", output_path));` to the top of this function to get better error messages.

**Review by wliue — CHANGES_REQUESTED** [review]
> Reviewed 15 of 29 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/30)* status: all files reviewed, 4 unresolved discussions (waiting on @EvgSkv, @kunyuchen, @lenjoy, @mpatel24, @my2457, and @tcsnfkx)

___
*[src/test/cc/wfa/virtual_people/core/labeler/labeler_integration_test.cc, line 1 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/30#-MuCwZb18NiDZF0Kk86X:-MuCwZb18NiDZF0Kk86Y:b-a0tvv1) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-core-serving/blob/a7ec07e1076534d3eee51247931f116c1c76522a/src/test/cc/wfa/virtual_people/core/labeler/labeler_integration_test.cc#L1)):*
> ```cpp
> // Copyright 2021 The Cross-Media Measurement Authors
> ```

Nit: should we use 2022 now?



_Code quote:_
```cpp
// Copyright 2021 
```
___
*[src/test/cc/wfa/virtual_people/core/labeler/test_data/labeler_output_01.textproto, line 2 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/30#-MuCxhN4DKTThXFTgUOk:-MuCxhN5Craw3wdTtUfd:b-u19r8s) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-core-serving/blob/a7ec07e1076534d3eee51247931f116c1c76522a/src/test/cc/wfa/virtual_people/core/labeler/test_data/labeler_output_01.textproto#L2)):*
> ```
> people {
>   virtual_person_id: 13000197489
> ```

Why there is no demo? Was the demo redistribution matrix removed from the model?

**Review by tcsnfkx — COMMENTED** [review]
> Dismissed @wliue from a discussion.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/30)* status: 28 of 29 files reviewed, all discussions resolved (waiting on @efoxepstein, @EvgSkv, @kunyuchen, @lenjoy, @mpatel24, @my2457, and @wliue)

___
*[src/test/cc/wfa/virtual_people/core/labeler/BUILD.bazel, line 23 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/30#-Mts-Tll9kGsAm2Ro-GU:-MuEs99n6dA-xiUj7ex-:bmcfaop) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-core-serving/blob/a7ec07e1076534d3eee51247931f116c1c76522a/src/test/cc/wfa/virtual_people/core/labeler/BUILD.bazel#L23)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Would something like this work? `data = glob(["//src/test/cc/wfa/virtual_people/core/labeler/test_data/labeler_input_*.textproto", "//src/test/cc/wfa/virtual_people/core/labeler/test_data/labeler_output_*.textproto"])`
</blockquote></details>

It does not work.
___
*[src/test/cc/wfa/virtual_people/core/labeler/test_data/labeler_output_01.textproto, line 2 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/30#-MuCxhN4DKTThXFTgUOk:-MuEuAzA8m9O8DvJHVym:bgbd1jk) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-core-serving/blob/a7ec07e1076534d3eee51247931f116c1c76522a/src/test/cc/wfa/virtual_people/core/labeler/test_data/labeler_output_01.textproto#L2)):*
<details><summary><i>Previously, wliue (Wei Liu) wrote…</i></summary><blockquote>

Why there is no demo? Was the demo redistribution matrix removed from the model?
</blockquote></details>

Only label or quantum_labels of LabelerEvent are written to output (https://github.com/world-federation-of-advertisers/virtual-people-core-serving/blob/main/src/main/cc/wfa/virtual_people/core/model/population_node_impl.cc#L126). This model has demo model, but does not write the redistributed demo to label or quantum_labels. We can update the model in next PR if we want.

**Review by wliue — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/30)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @EvgSkv, @kunyuchen, @lenjoy, @mpatel24, and @my2457)

**Review by mpatel24 — APPROVED** [review]

**Pull request merged**
