### PR TITLE
Add a tool that converts VID model to node list representation.

### PR DESCRIPTION
**Pull request by wliue**
This tool takes a model in single node representation, converts to
node list representation, then write to file in Riegeli format.

---
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/46)

### CODE REVIEW

**Review by wangyaopw — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/46)* status: 0 of 7 files reviewed, 1 unresolved discussion (waiting on @mpatel24, @stevenwarejones, @tcsnfkx, and @wliue)

___
*[`src/main/cc/wfa/virtual_people/core/model/model_serializer.cc` line 58 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/46#-N4EPvV_EXb9U-hb0PMw:-N4EPvVaDy0DNDa_Rxqu:b-r83qha) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-core-serving/blob/77721d27fd842b774ecac62e3fce4fa5d32ce138/src/main/cc/wfa/virtual_people/core/model/model_serializer.cc#L58)):*
> ```cpp
>     return absl::InvalidArgumentError(
>         absl::StrCat("AddChildren is called but this is not a branch node. ",
>                      node.DebugString()));
> ```

Do you want to truncate the string in the log? the size of the node proto can be pretty big.



_Code quote:_
```cpp
node.DebugString()
```

**Review by wliue — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/46)* status: 0 of 7 files reviewed, 1 unresolved discussion (waiting on @mpatel24, @stevenwarejones, @tcsnfkx, and @wangyaopw)

___
*[`src/main/cc/wfa/virtual_people/core/model/model_serializer.cc` line 58 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/46#-N4EPvV_EXb9U-hb0PMw:-N4QhiGb5pqqw9-LE_et:b-sn99h1) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-core-serving/blob/77721d27fd842b774ecac62e3fce4fa5d32ce138/src/main/cc/wfa/virtual_people/core/model/model_serializer.cc#L58)):*
<details><summary><i>Previously, wangyaopw (Yao Wang) wrote…</i></summary><blockquote>

Do you want to truncate the string in the log? the size of the node proto can be pretty big.
</blockquote></details>

Thanks for the review!
The intended usage of model_serializer is for Model Provider to convert the model to node list format before delivery. So I think truncation is fine here. We can revisit this if it becomes an issue.

**Review by wliue — COMMENTED** [review]
> Dismissed @wangyaopw from a discussion.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/46)* status: 0 of 7 files reviewed, all discussions resolved (waiting on @mpatel24, @stevenwarejones, and @tcsnfkx)

**Review by wangyaopw — APPROVED** [review]
> Reviewed 7 of 7 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/46)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @mpatel24, @stevenwarejones, and @tcsnfkx)

**Review by wangyaopw — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/46)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @mpatel24, @stevenwarejones, and @tcsnfkx)

**Review by stevenwarejones — APPROVED** [review]
> Reviewed 7 of 7 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/46)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @mpatel24 and @tcsnfkx)

**Pull request merged**
