### PR TITLE
Return error status when the probabilities are not normalized.

### PR DESCRIPTION
**Pull request by tcsnfkx**
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/23)

### CODE REVIEW

**Review by efoxepstein — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/23)* status: 0 of 5 files reviewed, 1 unresolved discussion (waiting on @EvgSkv, @kunyuchen, @lenjoy, @mpatel24, @my2457, @oliver-amzn, @tcsnfkx, and @wliue)

___
*[src/main/cc/wfa/virtual_people/core/model/utils/distributed_consistent_hashing.cc, line 33 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/23#-Mh-oIS14Mbk5e9a9psR:-Mh-oIS14Mbk5e9a9psS:b-pq9gnu) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-core-serving/blob/0e7b7d5fe40dc59eed373f6b16c54596ac93b321/src/main/cc/wfa/virtual_people/core/model/utils/distributed_consistent_hashing.cc#L33)):*
> ```cpp
> namespace wfa_virtual_people {
> 
> inline constexpr double kNormalizeError = 0.01;
> ```

https://abseil.io/tips/140 (see the section for source files)

**Review by efoxepstein — COMMENTED** [review]
> Reviewed 5 of 5 files at r1.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/23)* status: all files reviewed, 1 unresolved discussion (waiting on @EvgSkv, @kunyuchen, @lenjoy, @mpatel24, @my2457, @oliver-amzn, @tcsnfkx, and @wliue)

**Review by mpatel24 — APPROVED** [review]

**Review by tcsnfkx — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/23)* status: 4 of 5 files reviewed, 1 unresolved discussion (waiting on @efoxepstein, @EvgSkv, @kunyuchen, @lenjoy, @my2457, @oliver-amzn, and @wliue)

___
*[src/main/cc/wfa/virtual_people/core/model/utils/distributed_consistent_hashing.cc, line 33 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/23#-Mh-oIS14Mbk5e9a9psR:-MhHCNP-64Jvi52BF4WP:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-core-serving/blob/0e7b7d5fe40dc59eed373f6b16c54596ac93b321/src/main/cc/wfa/virtual_people/core/model/utils/distributed_consistent_hashing.cc#L33)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

https://abseil.io/tips/140 (see the section for source files)
</blockquote></details>

Done.

**Review by wliue — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/23)* status: 4 of 5 files reviewed, 3 unresolved discussions (waiting on @efoxepstein, @EvgSkv, @kunyuchen, @lenjoy, @my2457, @oliver-amzn, and @tcsnfkx)

___
*[src/main/cc/wfa/virtual_people/core/model/utils/distributed_consistent_hashing.cc, line 33 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/23#-MhHZ1iV2cbHyJf4Dxlc:-MhHZ1iV2cbHyJf4Dxld:b-63dzem) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-core-serving/blob/ee78b7811daeeb56521c1727b4d34733ef0b9b61/src/main/cc/wfa/virtual_people/core/model/utils/distributed_consistent_hashing.cc#L33)):*
> ```
> 0.01
> ```

Error 0.01 is too large, and we should at least use 1e-4. To be on the safe side, how about 1e-7?  
___
*[src/test/cc/wfa/virtual_people/core/model/branch_node_impl_test.cc, line 159 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/23#-MhHXZNe7_TBw4UnL5q6:-MhHXZNe7_TBw4UnL5q7:bvjfgoj) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-core-serving/blob/ee78b7811daeeb56521c1727b4d34733ef0b9b61/src/test/cc/wfa/virtual_people/core/model/branch_node_impl_test.cc#L159)):*
<details><summary><i alt="summary">Quoted 5 lines of code…</i></summary>

> ```
>   // The branch node has 2 branches.
>   // One branch is selected with 40% chance, which is a population node always
>   // assigns virtual person id 10.
>   // The other branch is selected with 60% chance, which is a population node
>   // always assigns virtual person id 20.
> ```
</details>


Update this comment accordingly.

**Review by efoxepstein — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/23)* status: all files reviewed, 2 unresolved discussions (waiting on @EvgSkv, @kunyuchen, @lenjoy, @my2457, @oliver-amzn, and @tcsnfkx)

**Review by tcsnfkx — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/23)* status: 4 of 5 files reviewed, 2 unresolved discussions (waiting on @efoxepstein, @EvgSkv, @kunyuchen, @lenjoy, @my2457, @oliver-amzn, and @wliue)

___
*[src/main/cc/wfa/virtual_people/core/model/utils/distributed_consistent_hashing.cc, line 33 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/23#-MhHZ1iV2cbHyJf4Dxlc:-MhKuQ3j921vitIHpnCN:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-core-serving/blob/ee78b7811daeeb56521c1727b4d34733ef0b9b61/src/main/cc/wfa/virtual_people/core/model/utils/distributed_consistent_hashing.cc#L33)):*
<details><summary><i>Previously, wliue (Wei Liu) wrote…</i></summary><blockquote>

> ```
> 0.01
> ```

Error 0.01 is too large, and we should at least use 1e-4. To be on the safe side, how about 1e-7?  
</blockquote></details>

Done.
___
*[src/test/cc/wfa/virtual_people/core/model/branch_node_impl_test.cc, line 159 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/23#-MhHXZNe7_TBw4UnL5q6:-MhKuOwM1L1P3UjoCYjg:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-core-serving/blob/ee78b7811daeeb56521c1727b4d34733ef0b9b61/src/test/cc/wfa/virtual_people/core/model/branch_node_impl_test.cc#L159)):*
<details><summary><i>Previously, wliue (Wei Liu) wrote…</i></summary><blockquote>

> ```
>   // The branch node has 2 branches.
>   // One branch is selected with 40% chance, which is a population node always
>   // assigns virtual person id 10.
>   // The other branch is selected with 60% chance, which is a population node
>   // always assigns virtual person id 20.
> ```

Update this comment accordingly.
</blockquote></details>

Done.

**Review by efoxepstein — APPROVED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/23)* status: all files reviewed, 2 unresolved discussions (waiting on @EvgSkv, @kunyuchen, @lenjoy, @my2457, @oliver-amzn, and @wliue)

**Review by wliue — APPROVED** [review]
> Reviewed 3 of 5 files at r1, 1 of 1 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/23)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @EvgSkv, @kunyuchen, @lenjoy, @my2457, and @oliver-amzn)

**Pull request merged**
