### PR TITLE
StopNode Implementation

### PR DESCRIPTION
**Pull request by JuliethHernandez**
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/64)

### CODE REVIEW

**Review by wangyaopw — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/64)* status: 0 of 3 files reviewed, 2 unresolved discussions (waiting on @JuliethHernandez and @wangyaopw)

___
*[`src/main/kotlin/org/wfanet/virtualpeople/core/model/BUILD.bazel` line 16 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/64#-NBsV8oq7T0qcwob5dFn:-NBsV8oq7T0qcwob5dFo:b-8ls9sx) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-core-serving/blob/ab75a9f9c064f081aa541ad193b5f1872e691cef/src/main/kotlin/org/wfanet/virtualpeople/core/model/BUILD.bazel#L16)):*
> ```Starlark
>         "SparseUpdateMatrixImpl.kt",
>         "UpdateMatrixImpl.kt",
>         "StopNodeImpl.kt",
> ```

Change the order .

'S' should be above 'U'



_Code quote:_
```Starlark
"StopNodeImpl.kt",
```
___
*[`src/main/kotlin/org/wfanet/virtualpeople/core/model/StopNodeImpl.kt` line 29 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/64#-NBsVKfc21l4OPmUjQ9J:-NBsVKfc21l4OPmUjQ9K:b-sx8nex) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-core-serving/blob/ab75a9f9c064f081aa541ad193b5f1872e691cef/src/main/kotlin/org/wfanet/virtualpeople/core/model/StopNodeImpl.kt#L29)):*
> ```Kotlin
>   companion object {
>     fun build(nodeConfig: CompiledNode): ModelNode {
>       return StopNodeImpl(nodeConfig)
> ```

add 

```
      if (!nodeConfig.hasStopNode()) {
        error("This is not a stop node.")
      }
```



_Code quote:_
```Kotlin
return StopNodeImpl(nodeConfig)
```

**Review by JuliethHernandez — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/64)* status: 0 of 3 files reviewed, 2 unresolved discussions (waiting on @wangyaopw)

___
*[`src/main/kotlin/org/wfanet/virtualpeople/core/model/BUILD.bazel` line 16 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/64#-NBsV8oq7T0qcwob5dFn:-NBsWuDL1pKFMaP2Hmm9:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-core-serving/blob/ab75a9f9c064f081aa541ad193b5f1872e691cef/src/main/kotlin/org/wfanet/virtualpeople/core/model/BUILD.bazel#L16)):*
<details><summary><i>Previously, wangyaopw (Yao Wang) wrote…</i></summary><blockquote>

Change the order .

'S' should be above 'U'


</blockquote></details>

Done.
___
*[`src/main/kotlin/org/wfanet/virtualpeople/core/model/StopNodeImpl.kt` line 29 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/64#-NBsVKfc21l4OPmUjQ9J:-NBsWuzc66C8-lNaTGdQ:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-core-serving/blob/ab75a9f9c064f081aa541ad193b5f1872e691cef/src/main/kotlin/org/wfanet/virtualpeople/core/model/StopNodeImpl.kt#L29)):*
<details><summary><i>Previously, wangyaopw (Yao Wang) wrote…</i></summary><blockquote>

add 

```
      if (!nodeConfig.hasStopNode()) {
        error("This is not a stop node.")
      }
```
</blockquote></details>

Done.

**Review by wangyaopw — APPROVED** [review]
> Reviewed 1 of 3 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/64)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @JuliethHernandez)

**Review by wliue — APPROVED** [review]
> Reviewed 1 of 3 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/64)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @tcsnfkx)

**Pull request merged**
