### PR TITLE
Remove support for empty pool and add check for cookie monster pool.

### PR DESCRIPTION
**Pull request by tcsnfkx**
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/71)

### CODE REVIEW

**Review by wangyaopw — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/71)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @EvgSkv, @mpatel24, @stevenwarejones, @tcsnfkx, and @wliue)

___
*[`src/main/cc/wfa/virtual_people/core/model/population_node_impl.cc` line 67 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/71#-NH0TSCj5sjkrRN8pG_N:-NH0TSCj5sjkrRN8pG_O:bh0w7b1) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-core-serving/blob/28a02f5749a93d242e1bda91164d62df5712270b/src/main/cc/wfa/virtual_people/core/model/population_node_impl.cc#L67)):*
> ```cpp
>         kCookieMonsterOffset) {
>       return absl::InvalidArgumentError(absl::StrCat(
>           "The virtual person pool contains ID range >= 10^18: ",
> ```

` >= 10^18` would confuse people I guess.

Maybe use  `range >= CookieMonsterOffset:", kCookieMonsterOffset`



_Code quote:_
```cpp
 >= 10^18
```

**Review by wliue — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/71)* status: 0 of 2 files reviewed, 5 unresolved discussions (waiting on @EvgSkv, @mpatel24, @stevenwarejones, @tcsnfkx, and @wangyaopw)

___
*[`src/main/cc/wfa/virtual_people/core/model/population_node_impl.cc` line 40 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/71#-NH0kGqPABm9wo9lWsej:-NH0kGqPABm9wo9lWsek:bnkztkn) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-core-serving/blob/28a02f5749a93d242e1bda91164d62df5712270b/src/main/cc/wfa/virtual_people/core/model/population_node_impl.cc#L40)):*
> ```cpp
> // TODO(@tcsnfkx): Merge these with the constants in virtual-people-training.
> // The offset and size of the cookie monster pools.
> // Except the cookie monster pool, any pool cannot use ID starting from
> ```

Nit: -> Except for



_Code quote:_
```cpp
Except
```
___
*[`src/main/cc/wfa/virtual_people/core/model/population_node_impl.cc` line 67 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/71#-NH0TSCj5sjkrRN8pG_N:-NH0l0nNEihtlAiOi9UV:b31ol69) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-core-serving/blob/28a02f5749a93d242e1bda91164d62df5712270b/src/main/cc/wfa/virtual_people/core/model/population_node_impl.cc#L67)):*
<details><summary><i>Previously, wangyaopw (Yao Wang) wrote…</i></summary><blockquote>

` >= 10^18` would confuse people I guess.

Maybe use  `range >= CookieMonsterOffset:", kCookieMonsterOffset`
</blockquote></details>

+1, or use "reserved ID range".
___
*[`src/main/cc/wfa/virtual_people/core/model/population_node_impl.cc` line 138 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/71#-NH0mCyT8tj8ZZK8T48p:-NH0mCyT8tj8ZZK8T48q:bkgsck8) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-core-serving/blob/28a02f5749a93d242e1bda91164d62df5712270b/src/main/cc/wfa/virtual_people/core/model/population_node_impl.cc#L138)):*
> ```cpp
>       absl::StrCat(random_seed_, event.acting_fingerprint()));
>   // Gets virtual person id from the pools.
>   uint64_t virtual_person_id =
> ```

Still want to check virtual_person_selector_ not NULL so it wouldn't crash. Return error for NULL.



_Code quote:_
```cpp
  uint64_t virtual_person_id =
      virtual_person_selector_->GetVirtualPersonId(seed);
```
___
*[`src/test/cc/wfa/virtual_people/core/model/population_node_impl_test.cc` line 42 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/71#-NH0mrG_03yPzc-XCUDt:-NH0mrG_03yPzc-XCUDu:b-s73oxb) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-core-serving/blob/28a02f5749a93d242e1bda91164d62df5712270b/src/test/cc/wfa/virtual_people/core/model/population_node_impl_test.cc#L42)):*
> ```cpp
> TEST(PopulationNodeImplTest, Apply) {
>   CompiledNode config;
>   // 999999999999999997 = 10^18 - 3
> ```

Could add comment that this tests a pool at the border of reserved range.



_Code quote:_
```cpp
// 999999999999999997 = 10^18 - 3
```
___
*[`src/test/cc/wfa/virtual_people/core/model/population_node_impl_test.cc` line 581 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/71#-NH0nDj6BxglMJc0QFtl:-NH0nDj6BxglMJc0QFtm:b-5vtmar) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-core-serving/blob/6b2fb3fc0ca699fcb33600d89b7c30c92fb8c89f/src/test/cc/wfa/virtual_people/core/model/population_node_impl_test.cc#L581)):*
> ```cpp
> 
> TEST(PopulationNodeImplTest, InvalidPools) {
>   // The node is invalid as the total pools size is 0.
> ```

Total size = 0 is still invalid pool, correct? Could keep the original cases.
Also add comment that the new case fails because it uses reserved id range.



_Code quote:_
```cpp
  // The node is invalid as the total pools size is 0.
```

**Review by tcsnfkx — COMMENTED** [review]
> Dismissed @wangyaopw and @wliue from 4 discussions.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/71)* status: 0 of 2 files reviewed, all discussions resolved (waiting on @EvgSkv, @mpatel24, and @stevenwarejones)

___
*[`src/main/cc/wfa/virtual_people/core/model/population_node_impl.cc` line 67 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/71#-NH0TSCj5sjkrRN8pG_N:-NHa-LMz4sgaqpT5qK9A:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-core-serving/blob/28a02f5749a93d242e1bda91164d62df5712270b/src/main/cc/wfa/virtual_people/core/model/population_node_impl.cc#L67)):*
<details><summary><i>Previously, wliue (Wei Liu) wrote…</i></summary><blockquote>

+1, or use "reserved ID range".
</blockquote></details>

Done.
___
*[`src/main/cc/wfa/virtual_people/core/model/population_node_impl.cc` line 138 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/71#-NH0mCyT8tj8ZZK8T48p:-NHa-OKO0QHspj8t-Q05:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-core-serving/blob/28a02f5749a93d242e1bda91164d62df5712270b/src/main/cc/wfa/virtual_people/core/model/population_node_impl.cc#L138)):*
<details><summary><i>Previously, wliue (Wei Liu) wrote…</i></summary><blockquote>

Still want to check virtual_person_selector_ not NULL so it wouldn't crash. Return error for NULL.
</blockquote></details>

Done.
___
*[`src/test/cc/wfa/virtual_people/core/model/population_node_impl_test.cc` line 42 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/71#-NH0mrG_03yPzc-XCUDt:-NHa-S1V37ayn7pLQQ6j:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-core-serving/blob/28a02f5749a93d242e1bda91164d62df5712270b/src/test/cc/wfa/virtual_people/core/model/population_node_impl_test.cc#L42)):*
<details><summary><i>Previously, wliue (Wei Liu) wrote…</i></summary><blockquote>

Could add comment that this tests a pool at the border of reserved range.
</blockquote></details>

Done.
___
*[`src/test/cc/wfa/virtual_people/core/model/population_node_impl_test.cc` line 581 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/71#-NH0nDj6BxglMJc0QFtl:-NHa-TH773JlDiVZz0s8:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-core-serving/blob/6b2fb3fc0ca699fcb33600d89b7c30c92fb8c89f/src/test/cc/wfa/virtual_people/core/model/population_node_impl_test.cc#L581)):*
<details><summary><i>Previously, wliue (Wei Liu) wrote…</i></summary><blockquote>

Total size = 0 is still invalid pool, correct? Could keep the original cases.
Also add comment that the new case fails because it uses reserved id range.
</blockquote></details>

Done.

**Review by wliue — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/71)* status: 0 of 2 files reviewed, all discussions resolved (waiting on @EvgSkv, @mpatel24, and @stevenwarejones)

**Review by wliue — APPROVED** [review]
> Reviewed 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/71)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @EvgSkv, @mpatel24, and @stevenwarejones)

**Pull request merged**
