### PR TITLE
Implement the kotlin jumpConsistentHash method.

### PR DESCRIPTION
**Pull request by wangyaopw**
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/53)

### CODE REVIEW

**Review by tcsnfkx — DISMISSED** [review]
> Reviewed 3 of 4 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/53)* status: 4 of 5 files reviewed, 1 unresolved discussion (waiting on @wangyaopw and @wliue)

___
*[`src/main/kotlin/org/wfanet/virtualpeople/core/model/utils/BUILD.bazel` line 6 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/53#-NBLWg1O8QQqLV4NBJJw:-NBLWg1O8QQqLV4NBJJx:b-xkh3az) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-core-serving/blob/9b1b6da7cd93da1e512da137266d205d2a4063fd/src/main/kotlin/org/wfanet/virtualpeople/core/model/utils/BUILD.bazel#L6)):*
> ```Starlark
> 
> kt_jvm_library(
>     name = "utils",
> ```

This will include any *.kt added in future. Typically we create separate BUILD targets and only include the libraries when used. Is it intended to create the *.kt target?

**Review by wangyaopw — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/53)* status: 4 of 5 files reviewed, 1 unresolved discussion (waiting on @tcsnfkx and @wliue)

___
*[`src/main/kotlin/org/wfanet/virtualpeople/core/model/utils/BUILD.bazel` line 6 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/53#-NBLWg1O8QQqLV4NBJJw:-NBNb1eJ3RYXSpsQNEEx:b2n60cu) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-core-serving/blob/9b1b6da7cd93da1e512da137266d205d2a4063fd/src/main/kotlin/org/wfanet/virtualpeople/core/model/utils/BUILD.bazel#L6)):*
<details><summary><i>Previously, tcsnfkx wrote…</i></summary><blockquote>

This will include any *.kt added in future. Typically we create separate BUILD targets and only include the libraries when used. Is it intended to create the *.kt target?
</blockquote></details>

I think it is fine to define a single library target for common or utils targets (if they are doing similar and related works). We have plenty of similar targets in our codebase

https://github.com/world-federation-of-advertisers/common-jvm/blob/main/src/main/kotlin/org/wfanet/measurement/common/BUILD.bazel#L5

If you prefer separate BUILD targets, I can refactor the build file after all my current PRs are merged. That would be easier

**Review by wliue — APPROVED** [review]
> Reviewed 4 of 4 files at r1, 1 of 1 files at r2, all commit messages.
> Dismissed @tcsnfkx from a discussion.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/53)* status: all files reviewed, 2 unresolved discussions (waiting on @tcsnfkx and @wangyaopw)

___
*[`src/test/kotlin/org/wfanet/virtualpeople/core/model/utils/ConsistentHashTest.kt` line 49 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/53#-NBP1uMREAgsDjTK5j1_:-NBP1uMREAgsDjTK5j1a:b-rzh1r7) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-core-serving/blob/9b1b6da7cd93da1e512da137266d205d2a4063fd/src/test/kotlin/org/wfanet/virtualpeople/core/model/utils/ConsistentHashTest.kt#L49)):*
> ```Kotlin
>   /**
>    * When using the same key, for any number of buckets n > 1, one of the following must be
>    * satisfied A. JumpConsistentHash(key, n) == JumpConsistentHash(key, n - 1)
> ```

Nit: add ':' and/or start a new line.



_Code quote:_
```Kotlin
satisfied
```

**Review by wangyaopw — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/53)* status: all files reviewed, 1 unresolved discussion (waiting on @tcsnfkx)

___
*[`src/test/kotlin/org/wfanet/virtualpeople/core/model/utils/ConsistentHashTest.kt` line 49 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/53#-NBP1uMREAgsDjTK5j1_:-NBPLoRq--jmftwh-Pnc:bb6un1j) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-core-serving/blob/9b1b6da7cd93da1e512da137266d205d2a4063fd/src/test/kotlin/org/wfanet/virtualpeople/core/model/utils/ConsistentHashTest.kt#L49)):*
<details><summary><i>Previously, wliue (Wei Liu) wrote…</i></summary><blockquote>

Nit: add ':' and/or start a new line.
</blockquote></details>

Done

**Review by wliue — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/53)* status: all files reviewed, 1 unresolved discussion (waiting on @tcsnfkx)

**Review by wliue — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/53)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @tcsnfkx)

**Pull request merged**
