### PR TITLE
Set virtual person activities in PopulationNode.

### PR DESCRIPTION
**Pull request by tcsnfkx**
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/22)

### CODE REVIEW

**Review by efoxepstein — APPROVED** [review]
> Reviewed 3 of 3 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/22)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @EvgSkv, @kunyuchen, @lenjoy, @mpatel24, @my2457, @oliver-amzn, and @wliue)

**Review by efoxepstein — CHANGES_REQUESTED** [review]
> Reviewed 5 of 5 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/22)* status: all files reviewed, 1 unresolved discussion (waiting on @EvgSkv, @kunyuchen, @lenjoy, @mpatel24, @my2457, @oliver-amzn, @tcsnfkx, and @wliue)

___
*[src/main/cc/wfa/virtual_people/core/model/population_node_impl.cc, line 29 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/22#-MgRsx564gVb8Kq-6DyG:-MgRsx564gVb8Kq-6DyH:b-b0mh9z) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-core-serving/blob/52e3b22d1317fa66808642ce9f5a8f39a39a9c6e/src/main/cc/wfa/virtual_people/core/model/population_node_impl.cc#L29)):*
> ```cpp
> #include "src/farmhash.h"
> #include "src/main/proto/wfa/virtual_people/common/demographic.pb.h"
> #include "src/main/proto/wfa/virtual_people/common/label.pb.h"
> ```

Can you make sure the cc protos have a strip_include_prefix of "src/main/proto" so it's consistent with cc_library code? (This can happen in follow-up PRs)

**Review by tcsnfkx — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/22)* status: 5 of 8 files reviewed, 1 unresolved discussion (waiting on @efoxepstein, @EvgSkv, @kunyuchen, @lenjoy, @mpatel24, @my2457, @oliver-amzn, and @wliue)

___
*[src/main/cc/wfa/virtual_people/core/model/population_node_impl.cc, line 29 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/22#-MgRsx564gVb8Kq-6DyG:-MgS8C3ADYw4poItlABi:b-yyo3g5) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-core-serving/blob/52e3b22d1317fa66808642ce9f5a8f39a39a9c6e/src/main/cc/wfa/virtual_people/core/model/population_node_impl.cc#L29)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Can you make sure the cc protos have a strip_include_prefix of "src/main/proto" so it's consistent with cc_library code? (This can happen in follow-up PRs)
</blockquote></details>

cc_proto_library does not have a strip_include_prefix parameter. https://docs.bazel.build/versions/main/be/c-cpp.html#cc_proto_library

**Review by efoxepstein — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/22)* status: all files reviewed, 1 unresolved discussion (waiting on @EvgSkv, @kunyuchen, @lenjoy, @mpatel24, @my2457, @oliver-amzn, @tcsnfkx, and @wliue)

___
*[src/main/cc/wfa/virtual_people/core/model/population_node_impl.cc, line 29 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/22#-MgRsx564gVb8Kq-6DyG:-MgSCtn282I5GfG4nWsA:behxg9m) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-core-serving/blob/52e3b22d1317fa66808642ce9f5a8f39a39a9c6e/src/main/cc/wfa/virtual_people/core/model/population_node_impl.cc#L29)):*
<details><summary><i>Previously, tcsnfkx wrote…</i></summary><blockquote>

cc_proto_library does not have a strip_include_prefix parameter. https://docs.bazel.build/versions/main/be/c-cpp.html#cc_proto_library
</blockquote></details>

https://docs.bazel.build/versions/main/be/protocol-buffer.html#proto_library.strip_import_prefix

**Review by wliue — CHANGES_REQUESTED** [review]
> Reviewed 5 of 5 files at r3, 2 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/22)* status: all files reviewed, 3 unresolved discussions (waiting on @EvgSkv, @kunyuchen, @lenjoy, @mpatel24, @my2457, @oliver-amzn, and @tcsnfkx)

___
*[-- commits, line 1 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/22#-MgSNCBAAtPJwgYPTeoZ:-MgSNCBAAtPJwgYPTeo_:b-m7cbb2) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-core-serving/blob/5ffd123b3b5c3adb13e12b27204eab259c234ca0/-- commits#L1)):*
Is this file auto-generated? Is this supposed to be part of the change?
___
*[src/test/cc/wfa/virtual_people/core/model/population_node_impl_test.cc, line 79 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/22#-MgSPZvL7EzfYIIfqD8W:-MgSPZvL7EzfYIIfqD8X:b-4z1qsf) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-core-serving/blob/5ffd123b3b5c3adb13e12b27204eab259c234ca0/src/test/cc/wfa/virtual_people/core/model/population_node_impl_test.cc#L79)):*
> ```cpp
> }
> 
> TEST(PopulationNodeImplTest, TestApplyNoCorrectedDemo) {
> ```

Could add a test that virtual_person_activities is not empty when reaches the population node.

**Review by mpatel24 — APPROVED** [review]

**Review by efoxepstein — COMMENTED** [review]
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/22)* status: all files reviewed, 3 unresolved discussions (waiting on @EvgSkv, @kunyuchen, @lenjoy, @my2457, @oliver-amzn, and @tcsnfkx)

**Review by tcsnfkx — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/22)* status: all files reviewed, 3 unresolved discussions (waiting on @efoxepstein, @EvgSkv, @kunyuchen, @lenjoy, @my2457, @oliver-amzn, and @wliue)

___
*[-- commits, line 1 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/22#-MgSNCBAAtPJwgYPTeoZ:-Mgh0gBGELOCX85-Z3LT:b-g4b3j8) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-core-serving/blob/5ffd123b3b5c3adb13e12b27204eab259c234ca0/-- commits#L1)):*
<details><summary><i>Previously, wliue (Wei Liu) wrote…</i></summary><blockquote>

Is this file auto-generated? Is this supposed to be part of the change?
</blockquote></details>

I cannot find this file in the GitHub PR. Maybe generated by Reviewable?
___
*[src/main/cc/wfa/virtual_people/core/model/population_node_impl.cc, line 29 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/22#-MgRsx564gVb8Kq-6DyG:-Mgh2yr6AiNzIMXl8dap:b-e77qya) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-core-serving/blob/52e3b22d1317fa66808642ce9f5a8f39a39a9c6e/src/main/cc/wfa/virtual_people/core/model/population_node_impl.cc#L29)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

https://docs.bazel.build/versions/main/be/protocol-buffer.html#proto_library.strip_import_prefix
</blockquote></details>

Will do in future, as the protobufs are actually in another repo.
___
*[src/test/cc/wfa/virtual_people/core/model/population_node_impl_test.cc, line 79 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/22#-MgSPZvL7EzfYIIfqD8W:-Mgh2xQ7-jFZwGQNS10u:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-core-serving/blob/5ffd123b3b5c3adb13e12b27204eab259c234ca0/src/test/cc/wfa/virtual_people/core/model/population_node_impl_test.cc#L79)):*
<details><summary><i>Previously, wliue (Wei Liu) wrote…</i></summary><blockquote>

Could add a test that virtual_person_activities is not empty when reaches the population node.
</blockquote></details>

Done.

**Review by efoxepstein — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/22)* status: all files reviewed, 2 unresolved discussions (waiting on @EvgSkv, @kunyuchen, @lenjoy, @my2457, @oliver-amzn, and @wliue)

**Review by wliue — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/22)* status: all files reviewed, 2 unresolved discussions (waiting on @EvgSkv, @kunyuchen, @lenjoy, @my2457, @oliver-amzn, @tcsnfkx, and @wliue)

___
*[-- commits, line 1 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/22#-MgSNCBAAtPJwgYPTeoZ:-MghGwg1EraBwEoL9foR:bxkbhpi) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-core-serving/blob/5ffd123b3b5c3adb13e12b27204eab259c234ca0/-- commits#L1)):*
<details><summary><i>Previously, tcsnfkx wrote…</i></summary><blockquote>

I cannot find this file in the GitHub PR. Maybe generated by Reviewable?
</blockquote></details>

Seems so.

**Review by wliue — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/22)* status: all files reviewed, 1 unresolved discussion (waiting on @EvgSkv, @kunyuchen, @lenjoy, @my2457, @oliver-amzn, and @wliue)

**Review by wliue — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/22)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @EvgSkv, @kunyuchen, @lenjoy, @my2457, and @oliver-amzn)

**Pull request merged**
