### PR TITLE
Update the package version of common-cpp and virtual-person-common.

### PR DESCRIPTION
**Pull request by tcsnfkx**
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/25)

### CODE REVIEW

**Review by efoxepstein — APPROVED** [review]
> Reviewed 45 of 45 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/25)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @EvgSkv, @kunyuchen, @lenjoy, @mpatel24, @my2457, @oliver-amzn, and @wliue)

**Review by wliue — APPROVED** [review]
> Reviewed 45 of 45 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/25)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @EvgSkv, @kunyuchen, @lenjoy, @mpatel24, @my2457, and @oliver-amzn)

**Review by oliver-amzn — APPROVED** [review]
> Reviewed 45 of 45 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/25)* status: all files reviewed, 1 unresolved discussion (waiting on @EvgSkv, @kunyuchen, @lenjoy, @mpatel24, @my2457, and @tcsnfkx)

___
*[WORKSPACE, line 4 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/25#-MiO_BsN7L5N507Ai_eo:-MiO_BsOC4UfAjmrksOM:bq5jkdh) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-core-serving/blob/b70cc02e1d6571fc1961d0c5333644e688d05850/WORKSPACE#L4)):*
> ```Starlark
> 
> # Common-cpp
> http_archive(
> ```

nit: at some point it'd be nice to use `wfa_repo_archieve` like in cross-media-measurement here:
https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/main/build/wfa/repositories.bzl#L23

**Review by tcsnfkx — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/25)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @EvgSkv, @kunyuchen, @lenjoy, @mpatel24, and @my2457)

___
*[WORKSPACE, line 4 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/25#-MiO_BsN7L5N507Ai_eo:-MiSDlrT6GwGXZgRzv35:b-9whzin) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-core-serving/blob/b70cc02e1d6571fc1961d0c5333644e688d05850/WORKSPACE#L4)):*
<details><summary><i>Previously, oliver-amzn (Oliver) wrote…</i></summary><blockquote>

nit: at some point it'd be nice to use `wfa_repo_archieve` like in cross-media-measurement here:
https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/main/build/wfa/repositories.bzl#L23
</blockquote></details>

Thanks! We will use `wfa_repo_archieve` when it is moved to common-cpp repo.

**Pull request merged**
