### PR TITLE
Code style fix.

### PR DESCRIPTION
**Pull request by tcsnfkx**
Apply clang-format on C++ files.
Fix #ifndef macros.
Update the version of common-cpp and virtual-people-common.

Do not merge until https://github.com/world-federation-of-advertisers/virtual-people-common/pull/20 is merged and the TODO in WORKSPACE is resolved.

---
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/21)

### CODE REVIEW

**Review by mpatel24 — APPROVED** [review]

**Review by efoxepstein — CHANGES_REQUESTED** [review]
> Reviewed 25 of 25 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/21)* status: all files reviewed, 2 unresolved discussions (waiting on @EvgSkv, @kunyuchen, @lenjoy, @my2457, @oliver-amzn, @tcsnfkx, and @wliue)

___
*[WORKSPACE, line 7 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/21#-MgLduq56Y1WAkbJuLhU:-MgLduq56Y1WAkbJuLhV:bdhe4tt) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-core-serving/blob/23866ec4059167eb039d59633d0cb87798973143/WORKSPACE#L7)):*
> ```Starlark
>     name = "wfa_common_cpp",
>     sha256 = "63f923b38a3519c57d18db19b799d2040817c636be520c8c82830f7a0d63af47",
>     strip_prefix = "common-cpp-215be9e75b6d9f362d419e21c9804bd0d8d68916",
> ```

Could you reference release tag `v0.1.0` instead of a specific commit? https://github.com/world-federation-of-advertisers/common-cpp/releases/tag/v0.1.0

URL can be: `https://github.com/world-federation-of-advertisers/common-cpp/archive/v0.1.0.tar.gz` 
___
*[src/main/cc/wfa/virtual_people/core/model/utils/virtual_person_selector.cc, line 18 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/21#-MgLexkQ6UYRNypVQpvY:-MgLexkR9qRMZA-3tDTB:b-4zwwof) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-core-serving/blob/23866ec4059167eb039d59633d0cb87798973143/src/main/cc/wfa/virtual_people/core/model/utils/virtual_person_selector.cc#L18)):*
> ```cpp
> 
> #include <google/protobuf/repeated_field.h>
> ```

Please use quotes instead of <>s for non-stdlib things

**Review by tcsnfkx — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/21)* status: 23 of 25 files reviewed, 2 unresolved discussions (waiting on @efoxepstein, @EvgSkv, @kunyuchen, @lenjoy, @my2457, @oliver-amzn, and @wliue)

___
*[WORKSPACE, line 7 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/21#-MgLduq56Y1WAkbJuLhU:-MgM9STu9FBGjVZXTM8o:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-core-serving/blob/23866ec4059167eb039d59633d0cb87798973143/WORKSPACE#L7)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Could you reference release tag `v0.1.0` instead of a specific commit? https://github.com/world-federation-of-advertisers/common-cpp/releases/tag/v0.1.0

URL can be: `https://github.com/world-federation-of-advertisers/common-cpp/archive/v0.1.0.tar.gz` 
</blockquote></details>

Done.
___
*[src/main/cc/wfa/virtual_people/core/model/utils/virtual_person_selector.cc, line 18 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/21#-MgLexkQ6UYRNypVQpvY:-MgM9U9W78aYc7tca-J5:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-core-serving/blob/23866ec4059167eb039d59633d0cb87798973143/src/main/cc/wfa/virtual_people/core/model/utils/virtual_person_selector.cc#L18)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Please use quotes instead of <>s for non-stdlib things
</blockquote></details>

Done.

**Review by efoxepstein — APPROVED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/21)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @EvgSkv, @kunyuchen, @lenjoy, @my2457, @oliver-amzn, and @wliue)

**Review by oliver-amzn — COMMENTED** [review]
Are we missing lint checks/coverage if these code style issues weren't flagged before by the CI/CD? 

> Reviewed 20 of 25 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/21#-:-MgMLGZMD9-J7AgR--3Y:b-qfulwm)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @EvgSkv, @kunyuchen, @lenjoy, @my2457, and @wliue)

___
*[WORKSPACE, line 4 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/21#-MgMJ7D99GLrrdV5KH4V:-MgMJ7D99GLrrdV5KH4W:b-4ug8mn) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-core-serving/blob/0f2dfa14078bf9bd10e840ed9a23d1c464cc7579/WORKSPACE#L4)):*
> ```Starlark
> 
> # Common-cpp
> http_archive(
> ```

For the future, I like the `wfa_repo_archive` from here 
https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/main/build/wfa/repositories.bzl#L23-L47

Maybe we can move that into a common repo at some point and use it across the wfa repos? Might need to be a new repo to not repeat usage but I'd defer to the bazel experts here for best practices.

**Comment by tcsnfkx** [comment]
> Are we missing lint checks/coverage if these code style issues weren't flagged before by the CI/CD?
> 
> > Reviewed 20 of 25 files at r1, 2 of 2 files at r2, all commit messages.
> > _[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/21#-:-MgMLGZMD9-J7AgR--3Y:b-qfulwm)_ status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @EvgSkv, @kunyuchen, @lenjoy, @my2457, and @wliue)
> 
> _[WORKSPACE, line 4 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/21#-MgMJ7D99GLrrdV5KH4V:-MgMJ7D99GLrrdV5KH4W:b-4ug8mn) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-core-serving/blob/0f2dfa14078bf9bd10e840ed9a23d1c464cc7579/WORKSPACE#L4)):_
> 
> > ```python
> > # Common-cpp
> > http_archive(
> > ```
> 
> For the future, I like the `wfa_repo_archive` from here
> https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/main/build/wfa/repositories.bzl#L23-L47
> 
> Maybe we can move that into a common repo at some point and use it across the wfa repos? Might need to be a new repo to not repeat usage but I'd defer to the bazel experts here for best practices.

Thanks! I prefer this to be moved into "common-cpp" repo before being used in other repos.

**Review by oliver-amzn — APPROVED** [review]
> Reviewed 3 of 25 files at r1.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/21)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @EvgSkv, @kunyuchen, @lenjoy, @my2457, and @wliue)

___
*[WORKSPACE, line 4 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-core-serving/21#-MgMJ7D99GLrrdV5KH4V:-MgMvfid9OZCGlmLI_E_:b44tpx) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-core-serving/blob/0f2dfa14078bf9bd10e840ed9a23d1c464cc7579/WORKSPACE#L4)):*
<details><summary><i>Previously, tcsnfkx wrote…</i></summary><blockquote>

Thanks! I prefer this to be moved into "common-cpp" repo before being used in other repos.
</blockquote></details>

👍

**Pull request merged**
